//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/app/datastore/app/DSLibrary.java
//

#ifndef _FADSLibrary_H_
#define _FADSLibrary_H_

@class JavaLangInteger;

#import "JreEmulation.h"
#include "com/sponberg/fluid/datastore/DSBase.h"
#include "com/sponberg/fluid/datastore/SQLTable.h"

@interface FADSLibrary : FFTDSBase < FFTSQLTable > {
}

- (void)setIdWithJavaLangInteger:(JavaLangInteger *)id_;

- (JavaLangInteger *)getId;

- (void)setNameWithNSString:(NSString *)name;

- (NSString *)getName;

- (void)setAddress1WithNSString:(NSString *)address1;

- (NSString *)getAddress1;

- (void)setAddress2WithNSString:(NSString *)address2;

- (NSString *)getAddress2;

- (NSString *)_getTableName;

- (id)init;

@end

__attribute__((always_inline)) inline void FADSLibrary_init() {}

FOUNDATION_EXPORT NSString *FADSLibrary__table_;
J2OBJC_STATIC_FIELD_GETTER(FADSLibrary, _table_, NSString *)

FOUNDATION_EXPORT NSString *FADSLibrary_id__;
J2OBJC_STATIC_FIELD_GETTER(FADSLibrary, id__, NSString *)

FOUNDATION_EXPORT NSString *FADSLibrary_name_;
J2OBJC_STATIC_FIELD_GETTER(FADSLibrary, name_, NSString *)

FOUNDATION_EXPORT NSString *FADSLibrary_address1_;
J2OBJC_STATIC_FIELD_GETTER(FADSLibrary, address1_, NSString *)

FOUNDATION_EXPORT NSString *FADSLibrary_address2_;
J2OBJC_STATIC_FIELD_GETTER(FADSLibrary, address2_, NSString *)

typedef FADSLibrary ComSponbergAppDatastoreAppDSLibrary;

#endif // _FADSLibrary_H_
