//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/app/datastore/app/DSUser.java
//

#include "com/sponberg/app/datastore/app/DSUser.h"
#include "java/util/HashMap.h"

@implementation FADSUser

NSString * FADSUser__table_ = @"user";
NSString * FADSUser_name_ = @"name";
NSString * FADSUser_email_ = @"email";
NSString * FADSUser_phone_ = @"phone";

- (void)setNameWithNSString:(NSString *)name {
  (void) [((JavaUtilHashMap *) nil_chk(self->_data_)) putWithId:FADSUser_name_ withId:name];
}

- (NSString *)getName {
  return (NSString *) check_class_cast([((JavaUtilHashMap *) nil_chk(_data_)) getWithId:FADSUser_name_], [NSString class]);
}

- (void)setEmailWithNSString:(NSString *)email {
  (void) [((JavaUtilHashMap *) nil_chk(self->_data_)) putWithId:FADSUser_email_ withId:email];
}

- (NSString *)getEmail {
  return (NSString *) check_class_cast([((JavaUtilHashMap *) nil_chk(_data_)) getWithId:FADSUser_email_], [NSString class]);
}

- (void)setPhoneWithNSString:(NSString *)phone {
  (void) [((JavaUtilHashMap *) nil_chk(self->_data_)) putWithId:FADSUser_phone_ withId:phone];
}

- (NSString *)getPhone {
  return (NSString *) check_class_cast([((JavaUtilHashMap *) nil_chk(_data_)) getWithId:FADSUser_phone_], [NSString class]);
}

- (NSString *)_getTableName {
  return FADSUser__table_;
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "setNameWithNSString:", "setName", "V", 0x1, NULL },
    { "getName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setEmailWithNSString:", "setEmail", "V", 0x1, NULL },
    { "getEmail", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setPhoneWithNSString:", "setPhone", "V", 0x1, NULL },
    { "getPhone", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "_getTableName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "_table_", NULL, 0x19, "Ljava.lang.String;", &FADSUser__table_,  },
    { "name_", NULL, 0x19, "Ljava.lang.String;", &FADSUser_name_,  },
    { "email_", NULL, 0x19, "Ljava.lang.String;", &FADSUser_email_,  },
    { "phone_", NULL, 0x19, "Ljava.lang.String;", &FADSUser_phone_,  },
  };
  static J2ObjcClassInfo _FADSUser = { "DSUser", "com.sponberg.app.datastore.app", NULL, 0x1, 8, methods, 4, fields, 0, NULL};
  return &_FADSUser;
}

@end
