//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-external/com/eclipsesource/json/JsonLiteral.java
//

#ifndef _FFTJsonLiteral_H_
#define _FFTJsonLiteral_H_

@class FFTJsonWriter;

#import "JreEmulation.h"
#include "com/eclipsesource/json/JsonValue.h"

@interface FFTJsonLiteral : FFTJsonValue {
 @public
  NSString *value_;
}

- (id)initWithNSString:(NSString *)value;

- (void)writeWithFFTJsonWriter:(FFTJsonWriter *)writer;

- (NSString *)description;

- (BOOL)asBoolean;

- (BOOL)isNull;

- (BOOL)isBoolean;

- (BOOL)isTrue;

- (BOOL)isFalse;

- (NSUInteger)hash;

- (BOOL)isEqual:(id)object;

- (void)copyAllFieldsTo:(FFTJsonLiteral *)other;

@end

__attribute__((always_inline)) inline void FFTJsonLiteral_init() {}

J2OBJC_FIELD_SETTER(FFTJsonLiteral, value_, NSString *)

typedef FFTJsonLiteral ComEclipsesourceJsonJsonLiteral;

#endif // _FFTJsonLiteral_H_
