//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-external/com/eclipsesource/json/JsonWriter.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "com/eclipsesource/json/JsonArray.h"
#include "com/eclipsesource/json/JsonObject.h"
#include "com/eclipsesource/json/JsonValue.h"
#include "com/eclipsesource/json/JsonWriter.h"
#include "java/io/IOException.h"
#include "java/io/Writer.h"

BOOL FFTJsonWriter_initialized = NO;

@implementation FFTJsonWriter

IOSCharArray * FFTJsonWriter_QUOT_CHARS_;
IOSCharArray * FFTJsonWriter_BS_CHARS_;
IOSCharArray * FFTJsonWriter_LF_CHARS_;
IOSCharArray * FFTJsonWriter_CR_CHARS_;
IOSCharArray * FFTJsonWriter_TAB_CHARS_;
IOSCharArray * FFTJsonWriter_UNICODE_2028_CHARS_;
IOSCharArray * FFTJsonWriter_UNICODE_2029_CHARS_;
IOSCharArray * FFTJsonWriter_HEX_DIGITS_;

- (id)initWithJavaIoWriter:(JavaIoWriter *)writer {
  if (self = [super init]) {
    self->writer_ = writer;
  }
  return self;
}

- (void)writeWithNSString:(NSString *)string {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithNSString:string];
}

- (void)writeStringWithNSString:(NSString *)string {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:'"'];
  int length = ((int) [((NSString *) nil_chk(string)) length]);
  int start = 0;
  IOSCharArray *chars = [IOSCharArray arrayWithLength:length];
  [string getChars:0 sourceEnd:length destination:chars destinationBegin:0];
  for (int index = 0; index < length; index++) {
    IOSCharArray *replacement = [FFTJsonWriter getReplacementCharsWithChar:IOSCharArray_Get(chars, index)];
    if (replacement != nil) {
      [writer_ writeWithCharArray:chars withInt:start withInt:index - start];
      [writer_ writeWithCharArray:replacement];
      start = index + 1;
    }
  }
  [writer_ writeWithCharArray:chars withInt:start withInt:length - start];
  [writer_ writeWithInt:'"'];
}

+ (IOSCharArray *)getReplacementCharsWithChar:(unichar)ch {
  IOSCharArray *replacement = nil;
  if (ch == '"') {
    replacement = FFTJsonWriter_QUOT_CHARS_;
  }
  else if (ch == '\\') {
    replacement = FFTJsonWriter_BS_CHARS_;
  }
  else if (ch == 0x000a) {
    replacement = FFTJsonWriter_LF_CHARS_;
  }
  else if (ch == 0x000d) {
    replacement = FFTJsonWriter_CR_CHARS_;
  }
  else if (ch == 0x0009) {
    replacement = FFTJsonWriter_TAB_CHARS_;
  }
  else if (ch == 0x2028) {
    replacement = FFTJsonWriter_UNICODE_2028_CHARS_;
  }
  else if (ch == 0x2029) {
    replacement = FFTJsonWriter_UNICODE_2029_CHARS_;
  }
  else if (ch >= FFTJsonWriter_CONTROL_CHARACTERS_START && ch <= FFTJsonWriter_CONTROL_CHARACTERS_END) {
    replacement = [IOSCharArray arrayWithChars:(unichar[]){ '\\', 'u', '0', '0', '0', '0' } count:6];
    (*IOSCharArray_GetRef(replacement, 4)) = IOSCharArray_Get(nil_chk(FFTJsonWriter_HEX_DIGITS_), (ch >> 4) & (int) 0x000f);
    (*IOSCharArray_GetRef(replacement, 5)) = IOSCharArray_Get(FFTJsonWriter_HEX_DIGITS_, ch & (int) 0x000f);
  }
  return replacement;
}

- (void)writeObjectWithFFTJsonObject:(FFTJsonObject *)object {
  [self writeBeginObject];
  BOOL first = YES;
  for (FFTJsonObject_Member * __strong member in nil_chk(object)) {
    if (!first) {
      [self writeObjectValueSeparator];
    }
    [self writeStringWithNSString:[((FFTJsonObject_Member *) nil_chk(member)) getName]];
    [self writeNameValueSeparator];
    [((FFTJsonValue *) nil_chk([member getValue])) writeWithFFTJsonWriter:self];
    first = NO;
  }
  [self writeEndObject];
}

- (void)writeBeginObject {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:'{'];
}

- (void)writeEndObject {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:'}'];
}

- (void)writeNameValueSeparator {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:':'];
}

- (void)writeObjectValueSeparator {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:','];
}

- (void)writeArrayWithFFTJsonArray:(FFTJsonArray *)array {
  [self writeBeginArray];
  BOOL first = YES;
  for (FFTJsonValue * __strong value in nil_chk(array)) {
    if (!first) {
      [self writeArrayValueSeparator];
    }
    [((FFTJsonValue *) nil_chk(value)) writeWithFFTJsonWriter:self];
    first = NO;
  }
  [self writeEndArray];
}

- (void)writeBeginArray {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:'['];
}

- (void)writeEndArray {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:']'];
}

- (void)writeArrayValueSeparator {
  [((JavaIoWriter *) nil_chk(writer_)) writeWithInt:','];
}

+ (void)initialize {
  if (self == [FFTJsonWriter class]) {
    FFTJsonWriter_QUOT_CHARS_ = [IOSCharArray arrayWithChars:(unichar[]){ '\\', '"' } count:2];
    FFTJsonWriter_BS_CHARS_ = [IOSCharArray arrayWithChars:(unichar[]){ '\\', '\\' } count:2];
    FFTJsonWriter_LF_CHARS_ = [IOSCharArray arrayWithChars:(unichar[]){ '\\', 'n' } count:2];
    FFTJsonWriter_CR_CHARS_ = [IOSCharArray arrayWithChars:(unichar[]){ '\\', 'r' } count:2];
    FFTJsonWriter_TAB_CHARS_ = [IOSCharArray arrayWithChars:(unichar[]){ '\\', 't' } count:2];
    FFTJsonWriter_UNICODE_2028_CHARS_ = [IOSCharArray arrayWithChars:(unichar[]){ '\\', 'u', '2', '0', '2', '8' } count:6];
    FFTJsonWriter_UNICODE_2029_CHARS_ = [IOSCharArray arrayWithChars:(unichar[]){ '\\', 'u', '2', '0', '2', '9' } count:6];
    FFTJsonWriter_HEX_DIGITS_ = [IOSCharArray arrayWithChars:(unichar[]){ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' } count:16];
    FFTJsonWriter_initialized = YES;
  }
}

- (void)copyAllFieldsTo:(FFTJsonWriter *)other {
  [super copyAllFieldsTo:other];
  other->writer_ = writer_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoWriter:", "JsonWriter", NULL, 0x0, NULL },
    { "writeWithNSString:", "write", "V", 0x0, "Ljava.io.IOException;" },
    { "writeStringWithNSString:", "writeString", "V", 0x0, "Ljava.io.IOException;" },
    { "getReplacementCharsWithChar:", "getReplacementChars", "[C", 0xa, NULL },
    { "writeObjectWithFFTJsonObject:", "writeObject", "V", 0x4, "Ljava.io.IOException;" },
    { "writeBeginObject", NULL, "V", 0x4, "Ljava.io.IOException;" },
    { "writeEndObject", NULL, "V", 0x4, "Ljava.io.IOException;" },
    { "writeNameValueSeparator", NULL, "V", 0x4, "Ljava.io.IOException;" },
    { "writeObjectValueSeparator", NULL, "V", 0x4, "Ljava.io.IOException;" },
    { "writeArrayWithFFTJsonArray:", "writeArray", "V", 0x4, "Ljava.io.IOException;" },
    { "writeBeginArray", NULL, "V", 0x4, "Ljava.io.IOException;" },
    { "writeEndArray", NULL, "V", 0x4, "Ljava.io.IOException;" },
    { "writeArrayValueSeparator", NULL, "V", 0x4, "Ljava.io.IOException;" },
  };
  static J2ObjcFieldInfo fields[] = {
    { "CONTROL_CHARACTERS_START_", NULL, 0x1a, "I", NULL, .constantValue.asInt = FFTJsonWriter_CONTROL_CHARACTERS_START },
    { "CONTROL_CHARACTERS_END_", NULL, 0x1a, "I", NULL, .constantValue.asInt = FFTJsonWriter_CONTROL_CHARACTERS_END },
    { "QUOT_CHARS_", NULL, 0x1a, "[C", &FFTJsonWriter_QUOT_CHARS_,  },
    { "BS_CHARS_", NULL, 0x1a, "[C", &FFTJsonWriter_BS_CHARS_,  },
    { "LF_CHARS_", NULL, 0x1a, "[C", &FFTJsonWriter_LF_CHARS_,  },
    { "CR_CHARS_", NULL, 0x1a, "[C", &FFTJsonWriter_CR_CHARS_,  },
    { "TAB_CHARS_", NULL, 0x1a, "[C", &FFTJsonWriter_TAB_CHARS_,  },
    { "UNICODE_2028_CHARS_", NULL, 0x1a, "[C", &FFTJsonWriter_UNICODE_2028_CHARS_,  },
    { "UNICODE_2029_CHARS_", NULL, 0x1a, "[C", &FFTJsonWriter_UNICODE_2029_CHARS_,  },
    { "HEX_DIGITS_", NULL, 0x1a, "[C", &FFTJsonWriter_HEX_DIGITS_,  },
    { "writer_", NULL, 0x14, "Ljava.io.Writer;", NULL,  },
  };
  static J2ObjcClassInfo _FFTJsonWriter = { "JsonWriter", "com.eclipsesource.json", NULL, 0x0, 13, methods, 11, fields, 0, NULL};
  return &_FFTJsonWriter;
}

@end
