//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-external/com/eclipsesource/json/WriterConfig.java
//

#include "com/eclipsesource/json/JsonWriter.h"
#include "com/eclipsesource/json/PrettyPrint.h"
#include "com/eclipsesource/json/WriterConfig.h"
#include "java/io/Writer.h"

BOOL FFTWriterConfig_initialized = NO;

@implementation FFTWriterConfig

FFTWriterConfig * FFTWriterConfig_MINIMAL_;
FFTWriterConfig * FFTWriterConfig_PRETTY_PRINT_;

- (FFTJsonWriter *)createWriterWithJavaIoWriter:(JavaIoWriter *)writer {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id)init {
  return [super init];
}

+ (void)initialize {
  if (self == [FFTWriterConfig class]) {
    FFTWriterConfig_MINIMAL_ = [[FFTWriterConfig_$1 alloc] init];
    FFTWriterConfig_PRETTY_PRINT_ = [FFTPrettyPrint indentWithSpacesWithInt:2];
    FFTWriterConfig_initialized = YES;
  }
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "createWriterWithJavaIoWriter:", "createWriter", "Lcom.eclipsesource.json.JsonWriter;", 0x400, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "MINIMAL_", NULL, 0x9, "Lcom.eclipsesource.json.WriterConfig;", &FFTWriterConfig_MINIMAL_,  },
    { "PRETTY_PRINT_", NULL, 0x9, "Lcom.eclipsesource.json.WriterConfig;", &FFTWriterConfig_PRETTY_PRINT_,  },
  };
  static J2ObjcClassInfo _FFTWriterConfig = { "WriterConfig", "com.eclipsesource.json", NULL, 0x401, 2, methods, 2, fields, 0, NULL};
  return &_FFTWriterConfig;
}

@end

@implementation FFTWriterConfig_$1

- (FFTJsonWriter *)createWriterWithJavaIoWriter:(JavaIoWriter *)writer {
  return [[FFTJsonWriter alloc] initWithJavaIoWriter:writer];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "createWriterWithJavaIoWriter:", "createWriter", "Lcom.eclipsesource.json.JsonWriter;", 0x0, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FFTWriterConfig_$1 = { "$1", "com.eclipsesource.json", "WriterConfig", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FFTWriterConfig_$1;
}

@end
