//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-external/com/eclipsesource/json/WritingBuffer.java
//

#ifndef _FFTJSONWritingBuffer_H_
#define _FFTJSONWritingBuffer_H_

@class IOSCharArray;

#import "JreEmulation.h"
#include "java/io/Writer.h"

@interface FFTJSONWritingBuffer : JavaIoWriter {
 @public
  JavaIoWriter *writer_;
  IOSCharArray *buffer_;
  int fill_;
}

- (id)initWithJavaIoWriter:(JavaIoWriter *)writer;

- (id)initWithJavaIoWriter:(JavaIoWriter *)writer
                   withInt:(int)bufferSize;

- (void)writeWithInt:(int)c;

- (void)writeWithCharArray:(IOSCharArray *)cbuf
                   withInt:(int)off
                   withInt:(int)len;

- (void)writeWithNSString:(NSString *)str
                  withInt:(int)off
                  withInt:(int)len;

- (void)flush;

- (void)close;

- (void)copyAllFieldsTo:(FFTJSONWritingBuffer *)other;

@end

__attribute__((always_inline)) inline void FFTJSONWritingBuffer_init() {}

J2OBJC_FIELD_SETTER(FFTJSONWritingBuffer, writer_, JavaIoWriter *)
J2OBJC_FIELD_SETTER(FFTJSONWritingBuffer, buffer_, IOSCharArray *)

typedef FFTJSONWritingBuffer ComEclipsesourceJsonWritingBuffer;

#endif // _FFTJSONWritingBuffer_H_
