//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/ApplicationLoader.java
//

#include "com/sponberg/fluid/ApplicationLoader.h"
#include "com/sponberg/fluid/FluidApp.h"

@interface FFTApplicationLoader : NSObject
@end

@implementation FFTApplicationLoader

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "load__WithFFTFluidApp:", "load", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _FFTApplicationLoader = { "ApplicationLoader", "com.sponberg.fluid", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_FFTApplicationLoader;
}

@end
