//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/ApplicationLoader.java
//

#ifndef _FFTApplicationLoader_H_
#define _FFTApplicationLoader_H_

@class FFTFluidApp;

#import "JreEmulation.h"
#include "com/sponberg/fluid/PlatformSpecifier.h"

@protocol FFTApplicationLoader < FFTPlatformSpecifier, NSObject, JavaObject >
- (void)load__WithFFTFluidApp:(FFTFluidApp *)app;

@end

__attribute__((always_inline)) inline void FFTApplicationLoader_init() {}

#define ComSponbergFluidApplicationLoader FFTApplicationLoader

#endif // _FFTApplicationLoader_H_
