//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/HttpService.java
//

#ifndef _FFTHttpService_H_
#define _FFTHttpService_H_

@class FFTHttpService_HttpAuthorization;
@class JavaUtilHashMap;
@protocol FFTHttpServiceCallback;

#import "JreEmulation.h"

@protocol FFTHttpService < NSObject, JavaObject >

- (void)getWithNSString:(NSString *)URL
    withJavaUtilHashMap:(JavaUtilHashMap *)parameters
withFFTHttpService_HttpAuthorization:(FFTHttpService_HttpAuthorization *)auth
withFFTHttpServiceCallback:(id<FFTHttpServiceCallback>)callback;

- (void)getBinaryWithNSString:(NSString *)URL
          withJavaUtilHashMap:(JavaUtilHashMap *)parameters
withFFTHttpService_HttpAuthorization:(FFTHttpService_HttpAuthorization *)auth
   withFFTHttpServiceCallback:(id<FFTHttpServiceCallback>)callback;

- (void)postWithNSString:(NSString *)URL
     withJavaUtilHashMap:(JavaUtilHashMap *)parameters
withFFTHttpService_HttpAuthorization:(FFTHttpService_HttpAuthorization *)auth
withFFTHttpServiceCallback:(id<FFTHttpServiceCallback>)callback;

- (void)putWithNSString:(NSString *)URL
    withJavaUtilHashMap:(JavaUtilHashMap *)parameters
withFFTHttpService_HttpAuthorization:(FFTHttpService_HttpAuthorization *)auth
withFFTHttpServiceCallback:(id<FFTHttpServiceCallback>)callback;

- (void)postRawWithNSString:(NSString *)URL
               withNSString:(NSString *)rawMessage
withFFTHttpService_HttpAuthorization:(FFTHttpService_HttpAuthorization *)auth
 withFFTHttpServiceCallback:(id<FFTHttpServiceCallback>)callback;

@end

__attribute__((always_inline)) inline void FFTHttpService_init() {}

#define ComSponbergFluidHttpService FFTHttpService

@interface FFTHttpService_HttpAuthorization : NSObject {
 @public
  NSString *username_;
  NSString *password_;
}

- (id)initWithNSString:(NSString *)username
          withNSString:(NSString *)password;

- (NSString *)getUsername;

- (NSString *)getPassword;

- (void)copyAllFieldsTo:(FFTHttpService_HttpAuthorization *)other;

@end

__attribute__((always_inline)) inline void FFTHttpService_HttpAuthorization_init() {}

J2OBJC_FIELD_SETTER(FFTHttpService_HttpAuthorization, username_, NSString *)
J2OBJC_FIELD_SETTER(FFTHttpService_HttpAuthorization, password_, NSString *)

#endif // _FFTHttpService_H_
