//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/HttpServiceCallback.java
//

#include "com/sponberg/fluid/HttpServiceCallback.h"

@interface FFTHttpServiceCallback : NSObject
@end

@implementation FFTHttpServiceCallback

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "successWithFFTHttpServiceCallback_HttpResponse:", "success", "V", 0x401, NULL },
    { "failWithFFTHttpServiceCallback_HttpResponse:", "fail", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _FFTHttpServiceCallback = { "HttpServiceCallback", "com.sponberg.fluid", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_FFTHttpServiceCallback;
}

@end

@implementation FFTHttpServiceCallback_HttpResponse

- (id)initWithNSString:(NSString *)data
               withInt:(int)code {
  if (self = [super init]) {
    self->data_ = data;
    self->code_ = code;
  }
  return self;
}

- (NSString *)getData {
  return self->data_;
}

- (int)getCode {
  return self->code_;
}

- (void)copyAllFieldsTo:(FFTHttpServiceCallback_HttpResponse *)other {
  [super copyAllFieldsTo:other];
  other->code_ = code_;
  other->data_ = data_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:", "HttpResponse", NULL, 0x1, NULL },
    { "getData", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getCode", NULL, "I", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "data_", NULL, 0x0, "Ljava.lang.String;", NULL,  },
    { "code_", NULL, 0x0, "I", NULL,  },
  };
  static J2ObjcClassInfo _FFTHttpServiceCallback_HttpResponse = { "HttpResponse", "com.sponberg.fluid", "HttpServiceCallback", 0x9, 3, methods, 2, fields, 0, NULL};
  return &_FFTHttpServiceCallback_HttpResponse;
}

@end
