//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/ResourceService.java
//

#ifndef _FFTResourceService_H_
#define _FFTResourceService_H_

@class IOSByteArray;

#import "JreEmulation.h"

@protocol FFTResourceService < NSObject, JavaObject >

- (NSString *)getResourceAsStringWithNSString:(NSString *)dir
                                 withNSString:(NSString *)name;

- (IOSByteArray *)getResourceAsBytesWithNSString:(NSString *)dir
                                    withNSString:(NSString *)name;

- (void)saveResourceWithNSString:(NSString *)dir
                    withNSString:(NSString *)name
                   withByteArray:(IOSByteArray *)bytes
                     withBoolean:(BOOL)excludeFromBackup;

- (BOOL)resourceExistsWithNSString:(NSString *)dir
                      withNSString:(NSString *)name;

@end

__attribute__((always_inline)) inline void FFTResourceService_init() {}

#define ComSponbergFluidResourceService FFTResourceService

#endif // _FFTResourceService_H_
