//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/SystemService.java
//

#ifndef _FFTSystemService_H_
#define _FFTSystemService_H_

@class IOSObjectArray;
@protocol FFTCallbackFailable;
@protocol JavaLangRunnable;

#import "JreEmulation.h"

@protocol FFTSystemService < NSObject, JavaObject >

- (void)initiatePhoneCallWithNSString:(NSString *)phoneNumber OBJC_METHOD_FAMILY_NONE;

- (void)initiateEmailWithNSStringArray:(IOSObjectArray *)emails
                          withNSString:(NSString *)subject OBJC_METHOD_FAMILY_NONE;

- (void)runOnUiThreadWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;

- (BOOL)isOnUiThread;

- (void)getDeviceNotificationIdWithFFTCallbackFailable:(id<FFTCallbackFailable>)callback;

- (void)openBrowserWithWithNSString:(NSString *)url;

- (NSString *)getDeviceModel;

- (NSString *)getDeviceName;

- (NSString *)getDeviceSystemName;

- (NSString *)getDeviceSystemVersion;

- (NSString *)getAppVersion;

- (void)openAppStorePageForRating;

@end

__attribute__((always_inline)) inline void FFTSystemService_init() {}

#define ComSponbergFluidSystemService FFTSystemService

#endif // _FFTSystemService_H_
