//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/WebviewEventsManager.java
//

#ifndef _FFTWebviewEventsManager_H_
#define _FFTWebviewEventsManager_H_

@class FFTWebviewEventsManager_WebviewEventListenerGroup;
@class IOSObjectArray;
@class JavaUtilArrayList;
@class JavaUtilHashMap;
@protocol FFTWebviewActionListener;

#import "JreEmulation.h"

@interface FFTWebviewEventsManager : NSObject {
 @public
  FFTWebviewEventsManager_WebviewEventListenerGroup *rootEventListenerGroup_;
}

- (void)addEventListenerWithFFTWebviewActionListener:(id<FFTWebviewActionListener>)listener
                                   withNSStringArray:(IOSObjectArray *)keyPath;

- (void)actionPerformedWithNSString:(NSString *)keyPath
                       withNSString:(NSString *)userInfo;

- (BOOL)isListeningForTapAtWithNSString:(NSString *)viewPath;

- (FFTWebviewEventsManager_WebviewEventListenerGroup *)getEventListenerGroupWithFFTWebviewEventsManager_WebviewEventListenerGroup:(FFTWebviewEventsManager_WebviewEventListenerGroup *)group
                                                                                                                withNSStringArray:(IOSObjectArray *)tokens
                                                                                                                          withInt:(int)tokenIndex;

- (void)addEventListenerHelperWithFFTWebviewEventsManager_WebviewEventListenerGroup:(FFTWebviewEventsManager_WebviewEventListenerGroup *)group
                                                                  withNSStringArray:(IOSObjectArray *)tokens
                                                                            withInt:(int)tokenIndex
                                                       withFFTWebviewActionListener:(id<FFTWebviewActionListener>)listener;

- (IOSObjectArray *)getTokensFromPathWithNSString:(NSString *)keyPath;

- (id)init;

- (void)copyAllFieldsTo:(FFTWebviewEventsManager *)other;

@end

__attribute__((always_inline)) inline void FFTWebviewEventsManager_init() {}

J2OBJC_FIELD_SETTER(FFTWebviewEventsManager, rootEventListenerGroup_, FFTWebviewEventsManager_WebviewEventListenerGroup *)

typedef FFTWebviewEventsManager ComSponbergFluidWebviewEventsManager;

@interface FFTWebviewEventsManager_WebviewEventListenerGroup : NSObject {
 @public
  JavaUtilHashMap *listenerGroups_;
  JavaUtilArrayList *listeners_;
}

- (void)addListenerWithFFTWebviewActionListener:(id<FFTWebviewActionListener>)listener;

- (JavaUtilArrayList *)getListener;

- (FFTWebviewEventsManager_WebviewEventListenerGroup *)getWithNSString:(NSString *)key;

- (void)putWithNSString:(NSString *)key
withFFTWebviewEventsManager_WebviewEventListenerGroup:(FFTWebviewEventsManager_WebviewEventListenerGroup *)group;

- (id)init;

- (void)copyAllFieldsTo:(FFTWebviewEventsManager_WebviewEventListenerGroup *)other;

@end

__attribute__((always_inline)) inline void FFTWebviewEventsManager_WebviewEventListenerGroup_init() {}

J2OBJC_FIELD_SETTER(FFTWebviewEventsManager_WebviewEventListenerGroup, listenerGroups_, JavaUtilHashMap *)
J2OBJC_FIELD_SETTER(FFTWebviewEventsManager_WebviewEventListenerGroup, listeners_, JavaUtilArrayList *)

#endif // _FFTWebviewEventsManager_H_
