// This class is AutoGenerated code by the MakeDatastoreConstants tool.
// DO NOT EDIT.

package com.sponberg.fluid.datastore;

import com.sponberg.fluid.datastore.DSBase;
import com.sponberg.fluid.datastore.SQLTable;

public class DSLibrary extends DSBase implements SQLTable {

	public static final String _table = "library";

	public static final String id = "id";
	public static final String name = "name";
	public static final String address = "address";

	public void setId(Integer id) {
		this._data.put(DSLibrary.id, id);
	}

	public Integer getId() {
		 return (Integer) _data.get(DSLibrary.id);
	}

	public void setName(String name) {
		this._data.put(DSLibrary.name, name);
	}

	public String getName() {
		 return (String) _data.get(DSLibrary.name);
	}

	public void setAddress(String address) {
		this._data.put(DSLibrary.address, address);
	}

	public String getAddress() {
		 return (String) _data.get(DSLibrary.address);
	}

	public String _getTableName() {
		return DSLibrary._table;
	}

}