//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/util/CsvReader.java
//

#ifndef _FFTCsvReader_H_
#define _FFTCsvReader_H_

@class JavaIoBufferedReader;
@class JavaUtilArrayList;
@class JavaUtilHashMap;
@protocol JavaUtilCollection;

#import "JreEmulation.h"

@interface FFTCsvReader : NSObject {
 @public
  JavaUtilArrayList *attributes_;
  JavaUtilArrayList *rows_;
}

- (id)initWithJavaIoBufferedReader:(JavaIoBufferedReader *)inArg
                          withChar:(unichar)sep;

- (id)initWithJavaIoBufferedReader:(JavaIoBufferedReader *)inArg
                          withChar:(unichar)sep
                           withInt:(int)headerRows;

- (BOOL)containsAttributeWithNSString:(NSString *)s;

- (JavaUtilArrayList *)getAttributes;

- (JavaUtilArrayList *)getRows;

- (JavaUtilArrayList *)tokenizeWithNSString:(NSString *)line
                                   withChar:(unichar)sep;

- (void)copyAllFieldsTo:(FFTCsvReader *)other;

@end

__attribute__((always_inline)) inline void FFTCsvReader_init() {}

J2OBJC_FIELD_SETTER(FFTCsvReader, attributes_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(FFTCsvReader, rows_, JavaUtilArrayList *)

typedef FFTCsvReader ComSponbergFluidUtilCsvReader;

@interface FFTCsvReader_Attribute : NSObject {
 @public
  int index_;
  NSString *name_;
}

- (id)initWithInt:(int)index
     withNSString:(NSString *)name;

- (int)getIndex;

- (NSString *)getName;

- (void)copyAllFieldsTo:(FFTCsvReader_Attribute *)other;

@end

__attribute__((always_inline)) inline void FFTCsvReader_Attribute_init() {}

J2OBJC_FIELD_SETTER(FFTCsvReader_Attribute, name_, NSString *)

@interface FFTCsvReader_Row : NSObject {
 @public
  JavaUtilHashMap *map_;
}

- (NSString *)getWithNSString:(NSString *)key;

- (id<JavaUtilCollection>)getAllValues;

- (id)init;

- (void)copyAllFieldsTo:(FFTCsvReader_Row *)other;

@end

__attribute__((always_inline)) inline void FFTCsvReader_Row_init() {}

J2OBJC_FIELD_SETTER(FFTCsvReader_Row, map_, JavaUtilHashMap *)

#endif // _FFTCsvReader_H_
