//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/util/HmacUtil.java
//

#ifndef _FFTHmacUtil_H_
#define _FFTHmacUtil_H_

@class JavaLangInteger;

#import "JreEmulation.h"

@interface FFTHmacUtil : NSObject {
}

+ (NSString *)hmacBase64WithNSString:(NSString *)data
                        withNSString:(NSString *)key
                        withNSString:(NSString *)salt;

+ (JavaLangInteger *)hmacHashcodeWithNSString:(NSString *)data
                                 withNSString:(NSString *)key
                                 withNSString:(NSString *)salt;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTHmacUtil_init() {}

typedef FFTHmacUtil ComSponbergFluidUtilHmacUtil;

#endif // _FFTHmacUtil_H_
