//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/util/KeyValueList.java
//

#ifndef _FFTKeyValueList_H_
#define _FFTKeyValueList_H_

@protocol JavaUtilList;
@protocol JavaUtilSet;

#import "JreEmulation.h"

@protocol FFTKeyValueList < NSObject, JavaObject >

- (BOOL)containsWithNSString:(NSString *)key;

- (id<JavaUtilList>)getWithNSString:(NSString *)key;

- (id<FFTKeyValueList>)getWithValueWithNSString:(NSString *)key
                                   withNSString:(NSString *)value;

- (NSString *)getValue;

- (NSString *)getValueWithNSString:(NSString *)key;

- (id<JavaUtilList>)getValuesWithNSString:(NSString *)key;

- (id<JavaUtilSet>)keys;

@end

__attribute__((always_inline)) inline void FFTKeyValueList_init() {}

#define ComSponbergFluidUtilKeyValueList FFTKeyValueList

#endif // _FFTKeyValueList_H_
