//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/util/LRUCache.java
//

#ifndef _FFTLRUCache_H_
#define _FFTLRUCache_H_

@class JavaUtilArrayList;
@protocol FFTLRUCache_RemovedListener;
@protocol JavaUtilMap_Entry;

#import "JreEmulation.h"
#include "java/lang/Runnable.h"
#include "java/util/LinkedHashMap.h"

@interface FFTLRUCache : JavaUtilLinkedHashMap {
 @public
  int maxEntries_;
  JavaUtilArrayList *removedListeners_;
}

- (id)initWithInt:(int)maxEntries;

- (BOOL)removeEldestEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)eldest;

- (void)addRemovedListenerWithFFTLRUCache_RemovedListener:(id<FFTLRUCache_RemovedListener>)listener;

- (void)copyAllFieldsTo:(FFTLRUCache *)other;

@end

__attribute__((always_inline)) inline void FFTLRUCache_init() {}

J2OBJC_FIELD_SETTER(FFTLRUCache, removedListeners_, JavaUtilArrayList *)

typedef FFTLRUCache ComSponbergFluidUtilLRUCache;

@protocol FFTLRUCache_RemovedListener < NSObject, JavaObject >

- (void)entryWasRemovedWithId:(id)key
                       withId:(id)entry_;

@end

__attribute__((always_inline)) inline void FFTLRUCache_RemovedListener_init() {}

@interface FFTLRUCache_$1 : NSObject < JavaLangRunnable > {
 @public
  FFTLRUCache *this$0_;
  id<JavaUtilMap_Entry> val$eldest_;
}

- (void)run;

- (id)initWithFFTLRUCache:(FFTLRUCache *)outer$
    withJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)capture$0;

@end

__attribute__((always_inline)) inline void FFTLRUCache_$1_init() {}

J2OBJC_FIELD_SETTER(FFTLRUCache_$1, this$0_, FFTLRUCache *)
J2OBJC_FIELD_SETTER(FFTLRUCache_$1, val$eldest_, id<JavaUtilMap_Entry>)

#endif // _FFTLRUCache_H_
