//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/DatastoreService.java
//

#ifndef _FFTDatastoreService_H_
#define _FFTDatastoreService_H_

@class FFTSQLInsert;
@class FFTSQLQuery;
@class FFTSQLQueryJoin3;
@class FFTSQLQueryJoin4;
@class FFTSQLQueryJoin;
@class FFTSQLResultList;
@class FFTSQLUpdate;
@class JavaLangLong;

#import "JreEmulation.h"

@protocol FFTDatastoreService < NSObject, JavaObject >

- (BOOL)doesDatabaseExistWithNSString:(NSString *)databaseName;

- (BOOL)doesBackupExistWithNSString:(NSString *)databaseName;

- (void)restoreBackupWithNSString:(NSString *)databaseName;

- (void)backupDatabaseWithNSString:(NSString *)databaseName;

- (void)deleteBackupWithNSString:(NSString *)databaseName;

- (BOOL)deployDatabaseFromBundleWithNSString:(NSString *)databaseName;

- (void)openDatabaseWithNSString:(NSString *)databaseName;

- (void)closeDatabase;

- (void)deleteDatabaseWithNSString:(NSString *)databaseName;

- (void)executeRawStatementWithNSString:(NSString *)statement;

- (FFTSQLResultList *)queryWithFFTSQLQuery:(FFTSQLQuery *)query;

- (FFTSQLResultList *)queryWithFFTSQLQueryJoin:(FFTSQLQueryJoin *)query;

- (FFTSQLResultList *)queryWithFFTSQLQueryJoin3:(FFTSQLQueryJoin3 *)query;

- (FFTSQLResultList *)queryWithFFTSQLQueryJoin4:(FFTSQLQueryJoin4 *)query;

- (void)updateWithFFTSQLUpdate:(FFTSQLUpdate *)update;

- (JavaLangLong *)insertWithFFTSQLInsert:(FFTSQLInsert *)insert;

- (void)startTransaction;

- (void)commitTransaction;

- (void)rollbackTransaction;

@end

__attribute__((always_inline)) inline void FFTDatastoreService_init() {}

FOUNDATION_EXPORT NSString *FFTDatastoreService_backupSuffix_;
J2OBJC_STATIC_FIELD_GETTER(FFTDatastoreService, backupSuffix_, NSString *)

#define ComSponbergFluidDatastoreDatastoreService FFTDatastoreService

#endif // _FFTDatastoreService_H_
