//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/DatastoreManager.java
//

#ifndef _FFTDatastoreManager_H_
#define _FFTDatastoreManager_H_

@class FFTDatastoreManager_Database;
@class FFTDatastoreVersion;
@class FFTFluidApp;
@class IOSObjectArray;
@class JavaTextCollator;
@class JavaUtilArrayList;
@class JavaUtilHashMap;
@protocol FFTDatastoreService;
@protocol FFTKeyValueList;
@protocol FFTUpgradeListener;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "com/sponberg/fluid/ApplicationLoader.h"

@interface FFTDatastoreManager : NSObject < FFTApplicationLoader > {
 @public
  id<FFTKeyValueList> settings_;
  BOOL enabled_;
  NSString *defaultDatabaseName_;
  JavaUtilHashMap *databases_;
  JavaUtilHashMap *upgradeListeners_;
}

- (void)load__WithFFTFluidApp:(FFTFluidApp *)app;

- (void)createOrUpdateDatabaseWithFFTDatastoreManager_Database:(FFTDatastoreManager_Database *)database
                                               withFFTFluidApp:(FFTFluidApp *)app;

- (void)createDatabaseWithFFTDatastoreManager_Database:(FFTDatastoreManager_Database *)database
                                       withFFTFluidApp:(FFTFluidApp *)app;

- (void)notifyUpgradeListenerWithFFTDatastoreManager_Database:(FFTDatastoreManager_Database *)database
                                      withFFTDatastoreService:(id<FFTDatastoreService>)ds
                                      withFFTDatastoreVersion:(FFTDatastoreVersion *)toVersion;

- (void)upgradeDatabaseWithFFTDatastoreManager_Database:(FFTDatastoreManager_Database *)database
                                        withFFTFluidApp:(FFTFluidApp *)app
                                withFFTDatastoreVersion:(FFTDatastoreVersion *)fromVersion;

- (void)upgradeDatabaseHelperWithFFTDatastoreManager_Database:(FFTDatastoreManager_Database *)database
                                              withFFTFluidApp:(FFTFluidApp *)app
                                      withFFTDatastoreVersion:(FFTDatastoreVersion *)fromVersion;

- (void)upgradeDatabaseVersionWithFFTDatastoreManager_Database:(FFTDatastoreManager_Database *)database
                                               withFFTFluidApp:(FFTFluidApp *)app
                                       withFFTDatastoreVersion:(FFTDatastoreVersion *)version_;

- (void)executeRawStatementsWithNSString:(NSString *)statements;

- (void)setDatastoreVersionWithFFTDatastoreVersion:(FFTDatastoreVersion *)datastoreVersion;

- (FFTDatastoreVersion *)parseVersionNumberWithNSString:(NSString *)version_;

- (NSString *)formatVersionNumberWithFFTDatastoreVersion:(FFTDatastoreVersion *)version_;

- (NSString *)getVersionFileSuffixWithFFTDatastoreVersion:(FFTDatastoreVersion *)version_;

- (id<JavaUtilList>)getIndividualCreateStatementsWithNSString:(NSString *)createStatements;

- (BOOL)doesSchemaExist;

- (FFTDatastoreVersion *)getVersionOfDatabaseWithBoolean:(BOOL)ignoreHashMismatch;

- (void)populateVersionListWithFFTDatastoreManager_Database:(FFTDatastoreManager_Database *)database;

- (void)populateDatabasesMap;

- (FFTDatastoreManager_Database *)getDefaultDatabase;

- (FFTDatastoreManager_Database *)getDatabaseWithNSString:(NSString *)databaseName;

- (id<JavaUtilCollection>)getDatabases;

- (void)setUpgradeListenerWithFFTDatastoreVersion:(FFTDatastoreVersion *)toVersion
                           withFFTUpgradeListener:(id<FFTUpgradeListener>)listener;

+ (BOOL)isSQLKeywordWithNSString:(NSString *)str;

- (IOSObjectArray *)getSupportedPlatforms;

- (BOOL)isEnabled;

- (NSString *)getDefaultDatabaseName;

- (id)init;

- (void)copyAllFieldsTo:(FFTDatastoreManager *)other;

@end

FOUNDATION_EXPORT BOOL FFTDatastoreManager_initialized;
J2OBJC_STATIC_INIT(FFTDatastoreManager)

J2OBJC_FIELD_SETTER(FFTDatastoreManager, settings_, id<FFTKeyValueList>)
J2OBJC_FIELD_SETTER(FFTDatastoreManager, defaultDatabaseName_, NSString *)
J2OBJC_FIELD_SETTER(FFTDatastoreManager, databases_, JavaUtilHashMap *)
J2OBJC_FIELD_SETTER(FFTDatastoreManager, upgradeListeners_, JavaUtilHashMap *)

FOUNDATION_EXPORT IOSObjectArray *FFTDatastoreManager_sqlKeywords_;
J2OBJC_STATIC_FIELD_GETTER(FFTDatastoreManager, sqlKeywords_, IOSObjectArray *)

FOUNDATION_EXPORT JavaTextCollator *FFTDatastoreManager_englishCollator_;
J2OBJC_STATIC_FIELD_GETTER(FFTDatastoreManager, englishCollator_, JavaTextCollator *)

typedef FFTDatastoreManager ComSponbergFluidDatastoreDatastoreManager;

@interface FFTDatastoreManager_Database : NSObject {
 @public
  JavaUtilArrayList *versions_;
  FFTDatastoreVersion *currentVersion_;
  NSString *name_;
}

- (id)initWithNSString:(NSString *)name;

- (NSString *)getDatabaseName;

- (NSString *)getSimpleName;

- (void)copyAllFieldsTo:(FFTDatastoreManager_Database *)other;

@end

__attribute__((always_inline)) inline void FFTDatastoreManager_Database_init() {}

J2OBJC_FIELD_SETTER(FFTDatastoreManager_Database, versions_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(FFTDatastoreManager_Database, currentVersion_, FFTDatastoreVersion *)
J2OBJC_FIELD_SETTER(FFTDatastoreManager_Database, name_, NSString *)

#endif // _FFTDatastoreManager_H_
