//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/SQLExecutableQuery.java
//

#ifndef _FFTSQLExecutableQuery_H_
#define _FFTSQLExecutableQuery_H_

@class FFTSQLParameterizedStatement;
@class IOSByteArray;
@class JavaLangDouble;
@class JavaLangInteger;

#import "JreEmulation.h"

@protocol FFTSQLExecutableQuery < NSObject, JavaObject >

- (FFTSQLParameterizedStatement *)getParameterizedStatement;

- (BOOL)isAllowRefresh;

- (JavaLangInteger *)getLimit;

- (int)getOffset;

- (void)setOffsetWithInt:(int)offset;

- (void)stepQuery;

- (void)addResult;

- (void)setNullWithInt:(int)columnIndex
          withNSString:(NSString *)columnName;

- (void)setIntegerWithInt:(int)columnIndex
             withNSString:(NSString *)columnName
      withJavaLangInteger:(JavaLangInteger *)value;

- (void)setDoubleWithInt:(int)columnIndex
            withNSString:(NSString *)columnName
      withJavaLangDouble:(JavaLangDouble *)value;

- (void)setStringWithInt:(int)columnIndex
            withNSString:(NSString *)columnName
            withNSString:(NSString *)value;

- (void)setBinaryWithInt:(int)columnIndex
            withNSString:(NSString *)columnName
           withByteArray:(IOSByteArray *)value;

@end

__attribute__((always_inline)) inline void FFTSQLExecutableQuery_init() {}

#define ComSponbergFluidDatastoreSQLExecutableQuery FFTSQLExecutableQuery

#endif // _FFTSQLExecutableQuery_H_
