//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/SQLQueryJoin4.java
//

#include "IOSClass.h"
#include "com/sponberg/fluid/FluidApp.h"
#include "com/sponberg/fluid/GlobalState.h"
#include "com/sponberg/fluid/datastore/DatastoreException.h"
#include "com/sponberg/fluid/datastore/DatastoreService.h"
#include "com/sponberg/fluid/datastore/SQLQueryJoin4.h"
#include "com/sponberg/fluid/datastore/SQLQueryJoinBase.h"
#include "com/sponberg/fluid/datastore/SQLQueryResult.h"
#include "com/sponberg/fluid/datastore/SQLQueryResultTuple4.h"
#include "com/sponberg/fluid/datastore/SQLResultList.h"
#include "java/lang/IllegalAccessException.h"
#include "java/lang/InstantiationException.h"
#include "java/util/ArrayList.h"
#include "java/util/LinkedHashMap.h"

@implementation FFTSQLQueryJoin4

- (id)initWithIOSClass:(IOSClass *)queryResultClass
          withIOSClass:(IOSClass *)queryResultClass2
          withIOSClass:(IOSClass *)queryResultClass3
          withIOSClass:(IOSClass *)queryResultClass4
withJavaUtilLinkedHashMap:(JavaUtilLinkedHashMap *)columnsByTableName {
  if (self = [super initWithJavaUtilLinkedHashMap:columnsByTableName]) {
    self->results_ = [[FFTSQLResultList alloc] initWithFFTSQLExecutableQuery:self];
    [((JavaUtilArrayList *) nil_chk(resultClasses_)) addWithId:queryResultClass];
    [resultClasses_ addWithId:queryResultClass2];
    [resultClasses_ addWithId:queryResultClass3];
    [resultClasses_ addWithId:queryResultClass4];
  }
  return self;
}

- (void)addResult {
  tuple_ = [[FFTSQLQueryResultTuple4 alloc] init];
  [tuple_ createInstanceWithInt:0 withIOSClass:[self getQueryResultClassWithInt:0]];
  [tuple_ createInstanceWithInt:1 withIOSClass:[self getQueryResultClassWithInt:1]];
  [tuple_ createInstanceWithInt:2 withIOSClass:[self getQueryResultClassWithInt:2]];
  [tuple_ createInstanceWithInt:3 withIOSClass:[self getQueryResultClassWithInt:3]];
  [tuple_ createInstanceWithInt:4 withIOSClass:[self getQueryResultClassWithInt:4]];
  [((FFTSQLResultList *) nil_chk(results_)) addWithId:tuple_];
}

- (id<FFTSQLQueryResult>)getCurrentTupleResultWithInt:(int)resultIndex {
  return [((FFTSQLQueryResultTuple4 *) nil_chk(tuple_)) getResultWithInt:resultIndex];
}

- (void)stepQuery {
  (void) [((id<FFTDatastoreService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getDatastoreService])) queryWithFFTSQLQueryJoin4:self];
}

- (FFTSQLResultList *)getResults {
  return self->results_;
}

- (FFTSQLQueryResultTuple4 *)getTuple {
  return self->tuple_;
}

- (void)setResultsWithFFTSQLResultList:(FFTSQLResultList *)results {
  self->results_ = results;
}

- (void)setTupleWithFFTSQLQueryResultTuple4:(FFTSQLQueryResultTuple4 *)tuple {
  self->tuple_ = tuple;
}

- (NSString *)description {
  return [NSString stringWithFormat:@"SQLQueryJoin4(results=%@, tuple=%@)", [self getResults], [self getTuple]];
}

- (void)copyAllFieldsTo:(FFTSQLQueryJoin4 *)other {
  [super copyAllFieldsTo:other];
  other->results_ = results_;
  other->tuple_ = tuple_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithIOSClass:withIOSClass:withIOSClass:withIOSClass:withJavaUtilLinkedHashMap:", "SQLQueryJoin4", NULL, 0x1, NULL },
    { "addResult", NULL, "V", 0x1, "Ljava.lang.InstantiationException;Ljava.lang.IllegalAccessException;" },
    { "getCurrentTupleResultWithInt:", "getCurrentTupleResult", "Lcom.sponberg.fluid.datastore.SQLQueryResult;", 0x4, NULL },
    { "stepQuery", NULL, "V", 0x1, "Lcom.sponberg.fluid.datastore.DatastoreException;" },
    { "getResults", NULL, "Lcom.sponberg.fluid.datastore.SQLResultList;", 0x1, NULL },
    { "getTuple", NULL, "Lcom.sponberg.fluid.datastore.SQLQueryResultTuple4;", 0x1, NULL },
    { "setResultsWithFFTSQLResultList:", "setResults", "V", 0x1, NULL },
    { "setTupleWithFFTSQLQueryResultTuple4:", "setTuple", "V", 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "results_", NULL, 0x0, "Lcom.sponberg.fluid.datastore.SQLResultList;", NULL,  },
    { "tuple_", NULL, 0x0, "Lcom.sponberg.fluid.datastore.SQLQueryResultTuple4;", NULL,  },
  };
  static J2ObjcClassInfo _FFTSQLQueryJoin4 = { "SQLQueryJoin4", "com.sponberg.fluid.datastore", NULL, 0x1, 9, methods, 2, fields, 0, NULL};
  return &_FFTSQLQueryJoin4;
}

@end
