//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/SQLQueryResult.java
//

#include "IOSPrimitiveArray.h"
#include "com/sponberg/fluid/datastore/SQLQueryResult.h"
#include "java/lang/Double.h"
#include "java/lang/Integer.h"

@interface FFTSQLQueryResult : NSObject
@end

@implementation FFTSQLQueryResult

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "_setStringWithNSString:withNSString:", "_setString", "V", 0x401, NULL },
    { "_setIntegerWithNSString:withJavaLangInteger:", "_setInteger", "V", 0x401, NULL },
    { "_setDoubleWithNSString:withJavaLangDouble:", "_setDouble", "V", 0x401, NULL },
    { "_setNullWithNSString:", "_setNull", "V", 0x401, NULL },
    { "_setBlobWithNSString:withByteArray:", "_setBlob", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _FFTSQLQueryResult = { "SQLQueryResult", "com.sponberg.fluid.datastore", NULL, 0x201, 5, methods, 0, NULL, 0, NULL};
  return &_FFTSQLQueryResult;
}

@end
