//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/SQLQueryDefault.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/sponberg/fluid/datastore/SQLQueryDefault.h"
#include "com/sponberg/fluid/datastore/SQLQueryResultDefault.h"

@implementation FFTSQLQueryDefault

- (id)initWithNSString:(NSString *)tableName
     withNSStringArray:(IOSObjectArray *)selectColumns {
  return [super initWithNSString:tableName withIOSClass:[IOSClass classWithClass:[FFTSQLQueryResultDefault class]] withNSStringArray:selectColumns];
}

- (NSString *)description {
  return @"SQLQueryDefault()";
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withNSStringArray:", "SQLQueryDefault", NULL, 0x81, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
  };
  static const char *superclass_type_args[] = {"Lcom.sponberg.fluid.datastore.SQLQueryResultDefault;"};
  static J2ObjcClassInfo _FFTSQLQueryDefault = { "SQLQueryDefault", "com.sponberg.fluid.datastore", NULL, 0x1, 2, methods, 0, NULL, 1, superclass_type_args};
  return &_FFTSQLQueryDefault;
}

@end
