//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/SQLQueryResultTuple.java
//

#ifndef _FFTSQLQueryResultTuple_H_
#define _FFTSQLQueryResultTuple_H_

@class FFTSQLQueryResultDefault;
@class IOSClass;
@class JavaUtilArrayList;
@protocol FFTSQLQueryResult;

#import "JreEmulation.h"

@interface FFTSQLQueryResultTuple : NSObject {
 @public
  JavaUtilArrayList *results_;
}

- (void)createInstanceWithInt:(int)index
                 withIOSClass:(IOSClass *)queryResultClass;

- (id<FFTSQLQueryResult>)getResultWithInt:(int)index;

- (FFTSQLQueryResultDefault *)getDefault;

- (id)t1;

- (id)t2;

- (id)init;

- (void)copyAllFieldsTo:(FFTSQLQueryResultTuple *)other;

@end

__attribute__((always_inline)) inline void FFTSQLQueryResultTuple_init() {}

J2OBJC_FIELD_SETTER(FFTSQLQueryResultTuple, results_, JavaUtilArrayList *)

typedef FFTSQLQueryResultTuple ComSponbergFluidDatastoreSQLQueryResultTuple;

#endif // _FFTSQLQueryResultTuple_H_
