//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/datastore/SQLStatement.java
//

#include "com/sponberg/fluid/datastore/SQLParameterizedStatement.h"
#include "com/sponberg/fluid/datastore/SQLStatement.h"

@interface FFTSQLStatement : NSObject
@end

@implementation FFTSQLStatement

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getParameterizedStatement", NULL, "Lcom.sponberg.fluid.datastore.SQLParameterizedStatement;", 0x401, NULL },
  };
  static J2ObjcClassInfo _FFTSQLStatement = { "SQLStatement", "com.sponberg.fluid.datastore", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_FFTSQLStatement;
}

@end
