//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/app/ui/Details.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "com/sponberg/app/datastore/Datastore.h"
#include "com/sponberg/app/datastore/app/DSPhoto.h"
#include "com/sponberg/app/ui/Details.h"
#include "com/sponberg/app/ui/Screen.h"
#include "com/sponberg/fluid/FluidApp.h"
#include "com/sponberg/fluid/GlobalState.h"
#include "com/sponberg/fluid/datastore/DatastoreException.h"
#include "com/sponberg/fluid/layout/ActionListener.h"
#include "com/sponberg/fluid/layout/MenuButtonItem.h"
#include "com/sponberg/fluid/layout/ModalView.h"
#include "com/sponberg/fluid/layout/Screen.h"
#include "com/sponberg/fluid/layout/UIService.h"
#include "com/sponberg/fluid/util/Logger.h"
#include "java/lang/Integer.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"

@implementation FADetails

- (void)load__WithFFTFluidApp:(FFTFluidApp *)app {
  [self initializeMenuWithFFTFluidApp:app];
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([((FFTFluidApp *) nil_chk(app)) addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_Details_(), FAScreen_ScreenDetails_get_B_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FADetails_$1 alloc] init]];
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([app addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_Details_(), FAScreen_ScreenDetails_get_E_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FADetails_$2 alloc] init]];
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([app addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_Details_(), FAScreen_ScreenDetails_get_G_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FADetails_$3 alloc] init]];
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([app addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_Details_(), FAScreen_ScreenDetails_get_N_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FADetails_$4 alloc] init]];
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([app addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_Details_(), FAScreen_ScreenDetails_get_H_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FADetails_$5 alloc] init]];
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([app addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_Details_(), FAScreen_ScreenDetails_get_I_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FADetails_$6 alloc] init]];
}

- (void)initializeMenuWithFFTFluidApp:(FFTFluidApp *)app {
  FFTMenuButtonItem *item = [[FFTMenuButtonItem alloc] initWithNSString:FFTMenuButtonItem_get_SystemItemCamera_()];
  [item addActionListenerWithFFTActionListener:[[FADetails_$7 alloc] initWithFFTFluidApp:app]];
  [((id<JavaUtilList>) nil_chk([((FFTScreen *) nil_chk([((FFTFluidApp *) nil_chk(app)) getScreenWithNSString:FAScreen_get_Details_()])) getNavigationMenuItems])) addWithId:item];
  item = [[FFTMenuButtonItem alloc] initWithNSString:FFTMenuButtonItem_get_SystemItemAction_()];
  [((id<JavaUtilList>) nil_chk([((FFTScreen *) nil_chk([app getScreenWithNSString:FAScreen_get_Details_()])) getNavigationMenuItems])) addWithId:item];
}

- (IOSObjectArray *)getSupportedPlatforms {
  return nil;
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "load__WithFFTFluidApp:", "load", "V", 0x1, NULL },
    { "initializeMenuWithFFTFluidApp:", "initializeMenu", "V", 0x2, NULL },
    { "getSupportedPlatforms", NULL, "[Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _FADetails = { "Details", "com.sponberg.app.ui", NULL, 0x1, 4, methods, 0, NULL, 0, NULL};
  return &_FADetails;
}

@end

@implementation FADetails_$1

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) popLayout];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FADetails_$1 = { "$1", "com.sponberg.app.ui", "Details", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FADetails_$1;
}

@end

@implementation FADetails_$2

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) pushLayoutWithNSString:FAScreen_get_Measure_()];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FADetails_$2 = { "$2", "com.sponberg.app.ui", "Details", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FADetails_$2;
}

@end

@implementation FADetails_$3

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) pushLayoutWithNSString:FAScreen_get_Animate_()];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FADetails_$3 = { "$3", "com.sponberg.app.ui", "Details", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FADetails_$3;
}

@end

@implementation FADetails_$4

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  FFTModalView *modal = [[FFTModalView alloc] initWithNSString:FFTModalView_get_FluidLayoutFullScreen_()];
  [modal setUserDataWithId:@"SeparateActivity"];
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) showModalViewWithFFTModalView:modal];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FADetails_$4 = { "$4", "com.sponberg.app.ui", "Details", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FADetails_$4;
}

@end

@implementation FADetails_$5

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) pushLayoutWithNSString:FAScreen_get_TableForm_()];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FADetails_$5 = { "$5", "com.sponberg.app.ui", "Details", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FADetails_$5;
}

@end

@implementation FADetails_$6

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) pushLayoutWithNSString:FAScreen_get_DynamicTable_()];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FADetails_$6 = { "$6", "com.sponberg.app.ui", "Details", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FADetails_$6;
}

@end

@implementation FADetails_$7

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  FFTModalView *modalView = [[FFTModalView alloc] initWithNSString:FFTModalView_get_ImagePicker_()];
  JavaUtilHashMap *settings = [[JavaUtilHashMap alloc] init];
  (void) [settings putWithId:@"format" withId:@"jpg"];
  (void) [settings putWithId:@"quality" withId:@"90"];
  (void) [settings putWithId:@"maxWidth" withId:@"1024"];
  [modalView setUserDataWithId:settings];
  [modalView addActionListenerWithFFTModalView_ModalActionListener:[[FADetails_$7_$1 alloc] init]];
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(val$app_)) getUiService])) showModalViewWithFFTModalView:modalView];
}

- (id)initWithFFTFluidApp:(FFTFluidApp *)capture$0 {
  val$app_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "initWithFFTFluidApp:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$app_", NULL, 0x1012, "Lcom.sponberg.fluid.FluidApp;", NULL,  },
  };
  static J2ObjcClassInfo _FADetails_$7 = { "$7", "com.sponberg.app.ui", "Details", 0x8000, 2, methods, 1, fields, 0, NULL};
  return &_FADetails_$7;
}

@end

@implementation FADetails_$7_$1

- (void)modalCompleteWithId:(id)userDataObject {
  IOSByteArray *userData2 = (IOSByteArray *) check_class_cast(userDataObject, [IOSByteArray class]);
  [FFTLogger debugWithId:self withNSString:@"received byte array of length {}" withNSObjectArray:[IOSObjectArray arrayWithObjects:(id[]){ [JavaLangInteger valueOfWithInt:(int) [((IOSByteArray *) nil_chk(userData2)) count]] } count:1 type:[IOSClass classWithClass:[NSObject class]]]];
  FADSPhoto *photo = [[FADSPhoto alloc] init];
  [photo setDataWithByteArray:userData2];
  @try {
    [FADatastore insertPhotoWithFADSPhoto:photo];
  }
  @catch (FFTDatastoreException *e) {
    [FFTLogger errorWithId:self withJavaLangThrowable:e];
  }
}

- (void)modalCanceled {
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "modalCompleteWithId:", "modalComplete", "V", 0x1, NULL },
    { "modalCanceled", NULL, "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FADetails_$7_$1 = { "$1", "com.sponberg.app.ui", "Details$$7", 0x8000, 3, methods, 0, NULL, 0, NULL};
  return &_FADetails_$7_$1;
}

@end
