//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/app/ui/Details.java
//

#ifndef _FADetails_H_
#define _FADetails_H_

@class FFTActionListener_EventInfo;
@class FFTFluidApp;
@class IOSObjectArray;

#import "JreEmulation.h"
#include "com/sponberg/fluid/ApplicationLoader.h"
#include "com/sponberg/fluid/layout/ActionListenerAdapter.h"
#include "com/sponberg/fluid/layout/ModalView.h"

@interface FADetails : NSObject < FFTApplicationLoader > {
}

- (void)load__WithFFTFluidApp:(FFTFluidApp *)app;

- (void)initializeMenuWithFFTFluidApp:(FFTFluidApp *)app OBJC_METHOD_FAMILY_NONE;

- (IOSObjectArray *)getSupportedPlatforms;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_init() {}

typedef FADetails ComSponbergAppUiDetails;

@interface FADetails_$1 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_$1_init() {}

@interface FADetails_$2 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_$2_init() {}

@interface FADetails_$3 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_$3_init() {}

@interface FADetails_$4 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_$4_init() {}

@interface FADetails_$5 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_$5_init() {}

@interface FADetails_$6 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_$6_init() {}

@interface FADetails_$7 : FFTActionListenerAdapter {
 @public
  FFTFluidApp *val$app_;
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)initWithFFTFluidApp:(FFTFluidApp *)capture$0;

@end

__attribute__((always_inline)) inline void FADetails_$7_init() {}

J2OBJC_FIELD_SETTER(FADetails_$7, val$app_, FFTFluidApp *)

@interface FADetails_$7_$1 : NSObject < FFTModalView_ModalActionListener > {
}

- (void)modalCompleteWithId:(id)userDataObject;

- (void)modalCanceled;

- (id)init;

@end

__attribute__((always_inline)) inline void FADetails_$7_$1_init() {}

#endif // _FADetails_H_
