//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/app/ui/RecursionScreens.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/sponberg/app/ui/RecursionScreens.h"
#include "com/sponberg/app/ui/Screen.h"
#include "com/sponberg/fluid/FluidApp.h"
#include "com/sponberg/fluid/GlobalState.h"
#include "com/sponberg/fluid/layout/ActionListener.h"
#include "com/sponberg/fluid/layout/UIService.h"

@implementation FARecursionScreens

- (void)load__WithFFTFluidApp:(FFTFluidApp *)app {
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([((FFTFluidApp *) nil_chk(app)) addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_RecursionA_(), FAScreen_ScreenRecursionA_get_C_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FARecursionScreens_$1 alloc] init]];
  (void) [((FFTFluidApp_AddActionListenerBuilder *) nil_chk([app addActionListenerWithNSStringArray:[IOSObjectArray arrayWithObjects:(id[]){ FAScreen_get_RecursionB_(), FAScreen_ScreenRecursionB_get_C_() } count:2 type:[IOSClass classWithClass:[NSString class]]]])) listenerWithFFTActionListener:[[FARecursionScreens_$2 alloc] init]];
}

- (IOSObjectArray *)getSupportedPlatforms {
  return nil;
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "load__WithFFTFluidApp:", "load", "V", 0x1, NULL },
    { "getSupportedPlatforms", NULL, "[Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _FARecursionScreens = { "RecursionScreens", "com.sponberg.app.ui", NULL, 0x1, 3, methods, 0, NULL, 0, NULL};
  return &_FARecursionScreens;
}

@end

@implementation FARecursionScreens_$1

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) pushLayoutWithNSString:FAScreen_get_RecursionB_()];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FARecursionScreens_$1 = { "$1", "com.sponberg.app.ui", "RecursionScreens", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FARecursionScreens_$1;
}

@end

@implementation FARecursionScreens_$2

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info {
  [((id<FFTUIService>) nil_chk([((FFTFluidApp *) nil_chk(FFTGlobalState_get_fluidApp__())) getUiService])) pushLayoutWithNSString:FAScreen_get_RecursionA_()];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _FARecursionScreens_$2 = { "$2", "com.sponberg.app.ui", "RecursionScreens", 0x8000, 2, methods, 0, NULL, 0, NULL};
  return &_FARecursionScreens_$2;
}

@end
