//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/app/ui/RecursionScreens.java
//

#ifndef _FARecursionScreens_H_
#define _FARecursionScreens_H_

@class FFTActionListener_EventInfo;
@class FFTFluidApp;
@class IOSObjectArray;

#import "JreEmulation.h"
#include "com/sponberg/fluid/ApplicationLoader.h"
#include "com/sponberg/fluid/layout/ActionListenerAdapter.h"

@interface FARecursionScreens : NSObject < FFTApplicationLoader > {
}

- (void)load__WithFFTFluidApp:(FFTFluidApp *)app;

- (IOSObjectArray *)getSupportedPlatforms;

- (id)init;

@end

__attribute__((always_inline)) inline void FARecursionScreens_init() {}

typedef FARecursionScreens ComSponbergAppUiRecursionScreens;

@interface FARecursionScreens_$1 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FARecursionScreens_$1_init() {}

@interface FARecursionScreens_$2 : FFTActionListenerAdapter {
}

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)info;

- (id)init;

@end

__attribute__((always_inline)) inline void FARecursionScreens_$2_init() {}

#endif // _FARecursionScreens_H_
