//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/parser/ViewBehaviorFactory.java
//

#ifndef _FFTViewBehaviorFactory_H_
#define _FFTViewBehaviorFactory_H_

@class FFTViewBehavior;
@class FFTViewBehaviorTable;
@class JavaUtilHashMap;
@protocol FFTKeyValueList;
@protocol FFTViewBehaviorFactory_ViewBehaviorBuilder;
@protocol FFTViewBehaviorTable_RowProvider;

#import "JreEmulation.h"

@interface FFTViewBehaviorFactory : NSObject {
 @public
  JavaUtilHashMap *viewBehaviorBuilders_;
}

- (id)init;

- (void)register__WithNSString:(NSString *)key
withFFTViewBehaviorFactory_ViewBehaviorBuilder:(id<FFTViewBehaviorFactory_ViewBehaviorBuilder>)builder;

- (FFTViewBehavior *)getViewBehaviorWithNSString:(NSString *)key
                             withFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (void)registerDefaults;

- (FFTViewBehaviorTable *)getViewBehaviorTableWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id<FFTViewBehaviorTable_RowProvider>)buildProviderForRowLayoutWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id<FFTViewBehaviorTable_RowProvider>)buildProviderForTableLayoutWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (void)copyAllFieldsTo:(FFTViewBehaviorFactory *)other;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_init() {}

J2OBJC_FIELD_SETTER(FFTViewBehaviorFactory, viewBehaviorBuilders_, JavaUtilHashMap *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_SEGMENTED_CONTROL_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, SEGMENTED_CONTROL_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_SEARCHBAR_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, SEARCHBAR_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_TEXTFIELD_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, TEXTFIELD_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_URL_WEBVIEW_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, URL_WEBVIEW_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_WEBVIEW_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, WEBVIEW_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_SUBVIEW_REPEAT_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, SUBVIEW_REPEAT_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_SUBVIEW_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, SUBVIEW_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_IMAGE_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, IMAGE_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_SPACE_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, SPACE_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_TABLE_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, TABLE_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_BUTTON_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, BUTTON_, NSString *)

FOUNDATION_EXPORT NSString *FFTViewBehaviorFactory_LABEL_;
J2OBJC_STATIC_FIELD_GETTER(FFTViewBehaviorFactory, LABEL_, NSString *)

typedef FFTViewBehaviorFactory ComSponbergFluidParserViewBehaviorFactory;

@protocol FFTViewBehaviorFactory_ViewBehaviorBuilder < NSObject, JavaObject >

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_ViewBehaviorBuilder_init() {}

@interface FFTViewBehaviorFactory_$1 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$1_init() {}

@interface FFTViewBehaviorFactory_$2 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$2_init() {}

@interface FFTViewBehaviorFactory_$3 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
 @public
  FFTViewBehaviorFactory *this$0_;
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)initWithFFTViewBehaviorFactory:(FFTViewBehaviorFactory *)outer$;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$3_init() {}

J2OBJC_FIELD_SETTER(FFTViewBehaviorFactory_$3, this$0_, FFTViewBehaviorFactory *)

@interface FFTViewBehaviorFactory_$4 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$4_init() {}

@interface FFTViewBehaviorFactory_$5 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$5_init() {}

@interface FFTViewBehaviorFactory_$6 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$6_init() {}

@interface FFTViewBehaviorFactory_$7 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$7_init() {}

@interface FFTViewBehaviorFactory_$8 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$8_init() {}

@interface FFTViewBehaviorFactory_$9 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$9_init() {}

@interface FFTViewBehaviorFactory_$10 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$10_init() {}

@interface FFTViewBehaviorFactory_$11 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$11_init() {}

@interface FFTViewBehaviorFactory_$12 : NSObject < FFTViewBehaviorFactory_ViewBehaviorBuilder > {
}

- (FFTViewBehavior *)buildWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorFactory_$12_init() {}

#endif // _FFTViewBehaviorFactory_H_
