//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/ActionListenerAdapter.java
//

#include "com/sponberg/fluid/layout/ActionListener.h"
#include "com/sponberg/fluid/layout/ActionListenerAdapter.h"

@implementation FFTActionListenerAdapter

- (void)userTappedWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)eventInfo {
}

- (void)userChangedValueToWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)eventInfo
                                                   withId:(id)value {
}

- (void)userCancelled {
}

- (void)userScrolledToBottomWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)eventInfo {
}

- (void)userScrolledWithFloat:(float)percentage {
}

- (void)userBeginEditingWithFFTActionListener_EventInfo:(FFTActionListener_EventInfo *)eventInfo {
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "userTappedWithFFTActionListener_EventInfo:", "userTapped", "V", 0x1, NULL },
    { "userChangedValueToWithFFTActionListener_EventInfo:withId:", "userChangedValueTo", "V", 0x1, NULL },
    { "userCancelled", NULL, "V", 0x1, NULL },
    { "userScrolledToBottomWithFFTActionListener_EventInfo:", "userScrolledToBottom", "V", 0x1, NULL },
    { "userScrolledWithFloat:", "userScrolled", "V", 0x1, NULL },
    { "userBeginEditingWithFFTActionListener_EventInfo:", "userBeginEditing", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _FFTActionListenerAdapter = { "ActionListenerAdapter", "com.sponberg.fluid.layout", NULL, 0x1, 7, methods, 0, NULL, 0, NULL};
  return &_FFTActionListenerAdapter;
}

@end
