//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/Coord.java
//

#include "com/sponberg/fluid/layout/Coord.h"
#include "com/sponberg/fluid/layout/Subtractor.h"
#include "java/lang/Double.h"
#include "java/lang/RuntimeException.h"
#include "java/util/ArrayList.h"

@implementation FFTCoord

- (void)addSubtractorWithFFTSubtractor:(FFTSubtractor *)length {
  [((JavaUtilArrayList *) nil_chk(subtractors_)) addWithId:length];
}

- (BOOL)isRelativeToView {
  return NO;
}

- (BOOL)isRelativeToParent {
  return NO;
}

- (BOOL)isDynamic {
  return [self isRelativeToView] || [self isRelativeToParent];
}

- (JavaLangDouble *)getFixed {
  @throw [[JavaLangRuntimeException alloc] initWithNSString:@"Not implemented"];
}

- (NSString *)getRelativeId {
  @throw [[JavaLangRuntimeException alloc] initWithNSString:@"Not implemented"];
}

- (NSString *)getRelativeEdge {
  @throw [[JavaLangRuntimeException alloc] initWithNSString:@"Not implemented"];
}

- (id)init {
  if (self = [super init]) {
    subtractors_ = [[JavaUtilArrayList alloc] init];
  }
  return self;
}

- (void)copyAllFieldsTo:(FFTCoord *)other {
  [super copyAllFieldsTo:other];
  other->subtractors_ = subtractors_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "addSubtractorWithFFTSubtractor:", "addSubtractor", "V", 0x1, NULL },
    { "isRelativeToView", NULL, "Z", 0x1, NULL },
    { "isRelativeToParent", NULL, "Z", 0x1, NULL },
    { "isDynamic", NULL, "Z", 0x1, NULL },
    { "getFixed", NULL, "Ljava.lang.Double;", 0x1, NULL },
    { "getRelativeId", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getRelativeEdge", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "subtractors_", NULL, 0x0, "Ljava.util.ArrayList;", NULL,  },
  };
  static J2ObjcClassInfo _FFTCoord = { "Coord", "com.sponberg.fluid.layout", NULL, 0x401, 8, methods, 1, fields, 0, NULL};
  return &_FFTCoord;
}

@end
