//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/CoordRelativeToView.java
//

#ifndef _FFTCoordRelativeToView_H_
#define _FFTCoordRelativeToView_H_

@class JavaUtilArrayList;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/Coord.h"

@interface FFTCoordRelativeToView : FFTCoord {
 @public
  NSString *edge_;
  NSString *viewId_;
}

- (id)initWithNSString:(NSString *)edge
          withNSString:(NSString *)viewId
 withJavaUtilArrayList:(JavaUtilArrayList *)subtractors;

- (BOOL)isRelativeToView;

- (NSString *)getRelativeId;

- (NSString *)getRelativeEdge;

- (NSString *)description;

- (NSString *)getEdge;

- (NSString *)getViewId;

- (void)copyAllFieldsTo:(FFTCoordRelativeToView *)other;

@end

__attribute__((always_inline)) inline void FFTCoordRelativeToView_init() {}

J2OBJC_FIELD_SETTER(FFTCoordRelativeToView, edge_, NSString *)
J2OBJC_FIELD_SETTER(FFTCoordRelativeToView, viewId_, NSString *)

typedef FFTCoordRelativeToView ComSponbergFluidLayoutCoordRelativeToView;

#endif // _FFTCoordRelativeToView_H_
