//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/FluidView.java
//

#ifndef _FFTFluidView_H_
#define _FFTFluidView_H_

#import "JreEmulation.h"

@protocol FFTFluidView < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void FFTFluidView_init() {}

#define ComSponbergFluidLayoutFluidView FFTFluidView

#endif // _FFTFluidView_H_
