//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LayoutAction.java
//

#include "com/sponberg/fluid/layout/LayoutAction.h"

@interface FFTLayoutAction : NSObject
@end

@implementation FFTLayoutAction

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "run", NULL, "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _FFTLayoutAction = { "LayoutAction", "com.sponberg.fluid.layout", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_FFTLayoutAction;
}

@end
