//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthFixed.java
//

#ifndef _FFTLengthFixed_H_
#define _FFTLengthFixed_H_

@class JavaLangDouble;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/Length.h"

@interface FFTLengthFixed : FFTLength {
 @public
  double l_;
}

- (id)initWithDouble:(double)l;

- (JavaLangDouble *)getFixedLength;

- (NSString *)description;

- (double)getL;

- (void)copyAllFieldsTo:(FFTLengthFixed *)other;

@end

__attribute__((always_inline)) inline void FFTLengthFixed_init() {}

typedef FFTLengthFixed ComSponbergFluidLayoutLengthFixed;

#endif // _FFTLengthFixed_H_
