//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthRelativeToLayer.java
//

#include "com/sponberg/fluid/layout/LengthRelativeToLayer.h"
#include "java/util/ArrayList.h"

@implementation FFTLengthRelativeToLayer

- (id)initFFTLengthRelativeToLayerWithDouble:(double)ratio
                                     withInt:(int)layerIndex {
  if (self = [super init]) {
    self->ratio_ = ratio;
    self->layerIndex_ = layerIndex;
  }
  return self;
}

- (id)initWithDouble:(double)ratio
             withInt:(int)layerIndex {
  return [self initFFTLengthRelativeToLayerWithDouble:ratio withInt:layerIndex];
}

- (id)initWithDouble:(double)ratio
             withInt:(int)layerIndex
withJavaUtilArrayList:(JavaUtilArrayList *)subtractors {
  if (self = [self initFFTLengthRelativeToLayerWithDouble:ratio withInt:layerIndex]) {
    [super setSubtractorsWithJavaUtilArrayList:subtractors];
  }
  return self;
}

- (BOOL)relativeToLayer {
  return YES;
}

- (int)getLayerIndex {
  return layerIndex_;
}

- (double)getRatio {
  return ratio_;
}

- (NSString *)description {
  return [NSString stringWithFormat:@"LengthRelativeToLayer(ratio=%f, layerIndex=%d)", [self getRatio], [self getLayerIndex]];
}

- (void)copyAllFieldsTo:(FFTLengthRelativeToLayer *)other {
  [super copyAllFieldsTo:other];
  other->layerIndex_ = layerIndex_;
  other->ratio_ = ratio_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithDouble:withInt:", "LengthRelativeToLayer", NULL, 0x1, NULL },
    { "initWithDouble:withInt:withJavaUtilArrayList:", "LengthRelativeToLayer", NULL, 0x1, NULL },
    { "relativeToLayer", NULL, "Z", 0x1, NULL },
    { "getLayerIndex", NULL, "I", 0x1, NULL },
    { "getRatio", NULL, "D", 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "ratio_", NULL, 0x10, "D", NULL,  },
    { "layerIndex_", NULL, 0x10, "I", NULL,  },
  };
  static J2ObjcClassInfo _FFTLengthRelativeToLayer = { "LengthRelativeToLayer", "com.sponberg.fluid.layout", NULL, 0x1, 6, methods, 2, fields, 0, NULL};
  return &_FFTLengthRelativeToLayer;
}

@end
