//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthRelativeToView.java
//

#ifndef _FFTLengthRelativeToView_H_
#define _FFTLengthRelativeToView_H_

@class JavaUtilArrayList;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/Length.h"

@interface FFTLengthRelativeToView : FFTLength {
 @public
  double ratio_;
  NSString *viewId_;
}

- (id)initWithDouble:(double)ratio
        withNSString:(NSString *)viewId;

- (id)initWithDouble:(double)ratio
        withNSString:(NSString *)viewId
withJavaUtilArrayList:(JavaUtilArrayList *)subtractors;

- (BOOL)relativeToView;

- (NSString *)getRelativeId;

- (double)getRatio;

- (NSString *)description;

- (NSString *)getViewId;

- (void)copyAllFieldsTo:(FFTLengthRelativeToView *)other;

@end

__attribute__((always_inline)) inline void FFTLengthRelativeToView_init() {}

J2OBJC_FIELD_SETTER(FFTLengthRelativeToView, viewId_, NSString *)

typedef FFTLengthRelativeToView ComSponbergFluidLayoutLengthRelativeToView;

#endif // _FFTLengthRelativeToView_H_
