//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthRelativeToParent.java
//

#ifndef _FFTLengthRelativeToParent_H_
#define _FFTLengthRelativeToParent_H_

@class JavaUtilArrayList;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/Length.h"

@interface FFTLengthRelativeToParent : FFTLength {
 @public
  double ratio_;
}

- (id)initWithDouble:(double)ratio;

- (id)initWithDouble:(double)ratio
withJavaUtilArrayList:(JavaUtilArrayList *)subtractors;

- (BOOL)relativeToParent;

- (double)getRatio;

- (NSString *)description;

- (void)copyAllFieldsTo:(FFTLengthRelativeToParent *)other;

@end

__attribute__((always_inline)) inline void FFTLengthRelativeToParent_init() {}

typedef FFTLengthRelativeToParent ComSponbergFluidLayoutLengthRelativeToParent;

#endif // _FFTLengthRelativeToParent_H_
