//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthEquals.java
//

#ifndef _FFTLengthEquals_H_
#define _FFTLengthEquals_H_

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/Length.h"

@interface FFTLengthEquals : FFTLength {
 @public
  NSString *equalTo_;
}

- (id)initWithNSString:(NSString *)equalTo;

- (BOOL)equal;

- (NSString *)description;

- (NSString *)getEqualTo;

- (void)copyAllFieldsTo:(FFTLengthEquals *)other;

@end

__attribute__((always_inline)) inline void FFTLengthEquals_init() {}

J2OBJC_FIELD_SETTER(FFTLengthEquals, equalTo_, NSString *)

typedef FFTLengthEquals ComSponbergFluidLayoutLengthEquals;

#endif // _FFTLengthEquals_H_
