//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthSummation.java
//

#ifndef _FFTLengthSummation_H_
#define _FFTLengthSummation_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/Length.h"

@interface FFTLengthSummation : FFTLength {
 @public
  IOSObjectArray *sumOf_;
}

- (id)initWithNSStringArray:(IOSObjectArray *)sumOf;

- (BOOL)summation;

- (IOSObjectArray *)getSummationOf;

- (NSString *)description;

- (IOSObjectArray *)getSumOf;

- (void)copyAllFieldsTo:(FFTLengthSummation *)other;

@end

__attribute__((always_inline)) inline void FFTLengthSummation_init() {}

J2OBJC_FIELD_SETTER(FFTLengthSummation, sumOf_, IOSObjectArray *)

typedef FFTLengthSummation ComSponbergFluidLayoutLengthSummation;

#endif // _FFTLengthSummation_H_
