//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthFixed.java
//

#include "com/sponberg/fluid/layout/LengthFixed.h"
#include "java/lang/Double.h"

@implementation FFTLengthFixed

- (id)initWithDouble:(double)l {
  if (self = [super init]) {
    self->l_ = l;
  }
  return self;
}

- (JavaLangDouble *)getFixedLength {
  return [JavaLangDouble valueOfWithDouble:l_];
}

- (NSString *)description {
  return [NSString stringWithFormat:@"LengthFixed(l=%f)", [self getL]];
}

- (double)getL {
  return self->l_;
}

- (void)copyAllFieldsTo:(FFTLengthFixed *)other {
  [super copyAllFieldsTo:other];
  other->l_ = l_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithDouble:", "LengthFixed", NULL, 0x1, NULL },
    { "getFixedLength", NULL, "Ljava.lang.Double;", 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
    { "getL", NULL, "D", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "l_", NULL, 0x10, "D", NULL,  },
  };
  static J2ObjcClassInfo _FFTLengthFixed = { "LengthFixed", "com.sponberg.fluid.layout", NULL, 0x1, 4, methods, 1, fields, 0, NULL};
  return &_FFTLengthFixed;
}

@end
