//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/LengthEquals.java
//

#include "com/sponberg/fluid/layout/LengthEquals.h"

@implementation FFTLengthEquals

- (id)initWithNSString:(NSString *)equalTo {
  if (self = [super init]) {
    self->equalTo_ = equalTo;
  }
  return self;
}

- (BOOL)equal {
  return YES;
}

- (NSString *)description {
  return [NSString stringWithFormat:@"LengthEquals(equalTo=%@)", [self getEqualTo]];
}

- (NSString *)getEqualTo {
  return self->equalTo_;
}

- (void)copyAllFieldsTo:(FFTLengthEquals *)other {
  [super copyAllFieldsTo:other];
  other->equalTo_ = equalTo_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "LengthEquals", NULL, 0x1, NULL },
    { "equal", NULL, "Z", 0x1, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
    { "getEqualTo", NULL, "Ljava.lang.String;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "equalTo_", NULL, 0x10, "Ljava.lang.String;", NULL,  },
  };
  static J2ObjcClassInfo _FFTLengthEquals = { "LengthEquals", "com.sponberg.fluid.layout", NULL, 0x1, 4, methods, 1, fields, 0, NULL};
  return &_FFTLengthEquals;
}

@end
