//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/ModalView.java
//

#ifndef _FFTModalView_H_
#define _FFTModalView_H_

@class JavaUtilArrayList;
@protocol FFTModalView_ModalActionListener;

#import "JreEmulation.h"

@interface FFTModalView : NSObject {
 @public
  JavaUtilArrayList *actionListeners_;
  NSString *systemId_;
  id userData_;
  id fluidData_;
  id userSelection_;
  BOOL userCancelable_;
  NSString *tag_;
}

- (id)initWithNSString:(NSString *)systemId;

- (void)addActionListenerWithFFTModalView_ModalActionListener:(id<FFTModalView_ModalActionListener>)al;

- (void)modalCanceled;

- (void)modalCompleteWithId:(id)userDataObject;

- (NSString *)description;

- (JavaUtilArrayList *)getActionListeners;

- (NSString *)getSystemId;

- (id)getUserData;

- (id)getFluidData;

- (id)getUserSelection;

- (BOOL)isUserCancelable;

- (NSString *)getTag;

- (void)setActionListenersWithJavaUtilArrayList:(JavaUtilArrayList *)actionListeners;

- (void)setUserDataWithId:(id)userData;

- (void)setFluidDataWithId:(id)fluidData;

- (void)setUserSelectionWithId:(id)userSelection;

- (void)setUserCancelableWithBoolean:(BOOL)userCancelable;

- (void)setTagWithNSString:(NSString *)tag;

- (BOOL)isEqual:(id)o;

- (BOOL)canEqualWithId:(id)other;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(FFTModalView *)other;

@end

__attribute__((always_inline)) inline void FFTModalView_init() {}

J2OBJC_FIELD_SETTER(FFTModalView, actionListeners_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(FFTModalView, systemId_, NSString *)
J2OBJC_FIELD_SETTER(FFTModalView, userData_, id)
J2OBJC_FIELD_SETTER(FFTModalView, fluidData_, id)
J2OBJC_FIELD_SETTER(FFTModalView, userSelection_, id)
J2OBJC_FIELD_SETTER(FFTModalView, tag_, NSString *)

FOUNDATION_EXPORT NSString *FFTModalView_FluidLayout_;
J2OBJC_STATIC_FIELD_GETTER(FFTModalView, FluidLayout_, NSString *)

FOUNDATION_EXPORT NSString *FFTModalView_FluidLayoutFullScreen_;
J2OBJC_STATIC_FIELD_GETTER(FFTModalView, FluidLayoutFullScreen_, NSString *)

FOUNDATION_EXPORT NSString *FFTModalView_ImagePicker_;
J2OBJC_STATIC_FIELD_GETTER(FFTModalView, ImagePicker_, NSString *)

FOUNDATION_EXPORT NSString *FFTModalView_Confirmation_;
J2OBJC_STATIC_FIELD_GETTER(FFTModalView, Confirmation_, NSString *)

FOUNDATION_EXPORT NSString *FFTModalView_WaitingDialog_;
J2OBJC_STATIC_FIELD_GETTER(FFTModalView, WaitingDialog_, NSString *)

FOUNDATION_EXPORT NSString *FFTModalView_Custom_;
J2OBJC_STATIC_FIELD_GETTER(FFTModalView, Custom_, NSString *)

typedef FFTModalView ComSponbergFluidLayoutModalView;

@protocol FFTModalView_ModalActionListener < NSObject, JavaObject >

- (void)modalCompleteWithId:(id)userData;

- (void)modalCanceled;

@end

__attribute__((always_inline)) inline void FFTModalView_ModalActionListener_init() {}

@interface FFTModalView_ModalActionListenerAdapter : NSObject < FFTModalView_ModalActionListener > {
}

- (void)modalCompleteWithId:(id)userData;

- (void)modalCanceled;

- (id)init;

@end

__attribute__((always_inline)) inline void FFTModalView_ModalActionListenerAdapter_init() {}

@interface FFTModalView_ModalViewConfirmation : NSObject {
 @public
  NSString *title_;
  NSString *message_;
  NSString *ok_;
  NSString *cancel_;
}

- (NSString *)description;

- (NSString *)getTitle;

- (NSString *)getMessage;

- (NSString *)getOk;

- (NSString *)getCancel;

- (void)setTitleWithNSString:(NSString *)title;

- (void)setMessageWithNSString:(NSString *)message;

- (void)setOkWithNSString:(NSString *)ok;

- (void)setCancelWithNSString:(NSString *)cancel;

- (id)init;

- (void)copyAllFieldsTo:(FFTModalView_ModalViewConfirmation *)other;

@end

__attribute__((always_inline)) inline void FFTModalView_ModalViewConfirmation_init() {}

J2OBJC_FIELD_SETTER(FFTModalView_ModalViewConfirmation, title_, NSString *)
J2OBJC_FIELD_SETTER(FFTModalView_ModalViewConfirmation, message_, NSString *)
J2OBJC_FIELD_SETTER(FFTModalView_ModalViewConfirmation, ok_, NSString *)
J2OBJC_FIELD_SETTER(FFTModalView_ModalViewConfirmation, cancel_, NSString *)

@interface FFTModalView_ModalViewWaitingDialog : NSObject {
 @public
  NSString *title_;
  NSString *message_;
  BOOL willDisplayDimissMessage_;
  NSString *dismissTitle_;
  NSString *dismissMessage_;
  float dismissDelay_;
}

- (void)setDisplayDismissMessageWithNSString:(NSString *)title
                                withNSString:(NSString *)message
                                   withFloat:(float)dismissDelay;

- (NSString *)description;

- (NSString *)getTitle;

- (void)setTitleWithNSString:(NSString *)title;

- (NSString *)getMessage;

- (void)setMessageWithNSString:(NSString *)message;

- (BOOL)isWillDisplayDimissMessage;

- (NSString *)getDismissTitle;

- (NSString *)getDismissMessage;

- (float)getDismissDelay;

- (id)init;

- (void)copyAllFieldsTo:(FFTModalView_ModalViewWaitingDialog *)other;

@end

__attribute__((always_inline)) inline void FFTModalView_ModalViewWaitingDialog_init() {}

J2OBJC_FIELD_SETTER(FFTModalView_ModalViewWaitingDialog, title_, NSString *)
J2OBJC_FIELD_SETTER(FFTModalView_ModalViewWaitingDialog, message_, NSString *)
J2OBJC_FIELD_SETTER(FFTModalView_ModalViewWaitingDialog, dismissTitle_, NSString *)
J2OBJC_FIELD_SETTER(FFTModalView_ModalViewWaitingDialog, dismissMessage_, NSString *)

FOUNDATION_EXPORT NSString *FFTModalView_ModalViewWaitingDialog_kDefaultDismissTitle_;
J2OBJC_STATIC_FIELD_GETTER(FFTModalView_ModalViewWaitingDialog, kDefaultDismissTitle_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(FFTModalView_ModalViewWaitingDialog, kDefaultDismissTitle_, NSString *)

#endif // _FFTModalView_H_
