//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/UIService.java
//

#include "IOSObjectArray.h"
#include "com/sponberg/fluid/Callback.h"
#include "com/sponberg/fluid/layout/ModalView.h"
#include "com/sponberg/fluid/layout/UIService.h"

@interface FFTUIService : NSObject
@end

@implementation FFTUIService

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "removeSplashScreenWithNSString:withBoolean:", "removeSplashScreen", "V", 0x401, NULL },
    { "pushLayoutWithNSString:", "pushLayout", "V", 0x401, NULL },
    { "popLayout", NULL, "V", 0x401, NULL },
    { "setLayoutWithNSString:withBoolean:", "setLayout", "V", 0x401, NULL },
    { "showModalViewWithFFTModalView:", "showModalView", "V", 0x401, NULL },
    { "dismissModalViewWithFFTModalView:", "dismissModalView", "V", 0x401, NULL },
    { "closeCurrentLayout", NULL, "V", 0x401, NULL },
    { "showAlertWithNSString:withNSString:", "showAlert", "V", 0x401, NULL },
    { "showAlertWithNSString:withNSString:withFFTCallback:", "showAlert", "V", 0x401, NULL },
    { "computeHeightOfTextWithNSString:withFloat:withNSString:withFloat:", "computeHeightOfText", "F", 0x401, NULL },
    { "getScreenWidthInPixels", NULL, "I", 0x401, NULL },
    { "getScreenHeightInPixels", NULL, "I", 0x401, NULL },
    { "refreshMenuButtons", NULL, "V", 0x401, NULL },
    { "grabFocusForViewWithNSString:", "grabFocusForView", "V", 0x401, NULL },
    { "hideKeyboard", NULL, "V", 0x401, NULL },
    { "setLayoutStackWithNSStringArray:", "setLayoutStack", "V", 0x481, NULL },
    { "scrollToBottomWithNSString:withNSString:", "scrollToBottom", "V", 0x401, NULL },
    { "isOrientationLandscape", NULL, "Z", 0x401, NULL },
    { "getCurrentScreenId", NULL, "Ljava.lang.String;", 0x401, NULL },
  };
  static J2ObjcClassInfo _FFTUIService = { "UIService", "com.sponberg.fluid.layout", NULL, 0x201, 19, methods, 0, NULL, 0, NULL};
  return &_FFTUIService;
}

@end
