//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/ViewBehaviorSubview.java
//

#ifndef _FFTViewBehaviorSubview_H_
#define _FFTViewBehaviorSubview_H_

@class FFTView;
@class FFTViewPosition;
@protocol FFTKeyValueList;
@protocol JavaUtilCollection;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/ViewBehavior.h"

@interface FFTViewBehaviorSubview : FFTViewBehavior {
 @public
  NSString *subview_ViewBehaviorSubview_;
  NSString *key_;
  NSString *keyPrefix_;
}

- (id)initWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (BOOL)supportsHeightCompute;

- (float)computeHeightWithBoolean:(BOOL)landscape
                     withNSString:(NSString *)dataModelPrefix
                      withFFTView:(FFTView *)view
                      withBoolean:(BOOL)useCache;

- (void)precomputeViewPositionsWithBoolean:(BOOL)landscape
                              withNSString:(NSString *)precomputePrefix
                       withFFTViewPosition:(FFTViewPosition *)view
                              withNSString:(NSString *)viewPathPrefixView
                    withJavaUtilCollection:(id<JavaUtilCollection>)newViewPositions;

- (NSString *)description;

- (NSString *)getSubview;

- (NSString *)getKey;

- (NSString *)getKeyPrefix;

- (void)setSubviewWithNSString:(NSString *)subview;

- (void)copyAllFieldsTo:(FFTViewBehaviorSubview *)other;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorSubview_init() {}

J2OBJC_FIELD_SETTER(FFTViewBehaviorSubview, subview_ViewBehaviorSubview_, NSString *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorSubview, key_, NSString *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorSubview, keyPrefix_, NSString *)

typedef FFTViewBehaviorSubview ComSponbergFluidLayoutViewBehaviorSubview;

#endif // _FFTViewBehaviorSubview_H_
