//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/ViewBehaviorTable.java
//

#ifndef _FFTViewBehaviorTable_H_
#define _FFTViewBehaviorTable_H_

@class FFTTableLayout_TableSection;
@class FFTTableRow;
@class JavaLangBoolean;
@class JavaLangDouble;
@protocol FFTKeyValueList;
@protocol FFTViewBehaviorTable_RowProvider;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/ViewBehavior.h"

@interface FFTViewBehaviorTable : FFTViewBehavior {
 @public
  JavaLangDouble *rowHeight_;
  JavaLangDouble *sectionFooterHeight_;
  JavaLangDouble *sectionHeaderHeight_;
  JavaLangDouble *headerHeight_;
  JavaLangDouble *footerHeight_;
  JavaLangBoolean *scrollEnabled_;
  JavaLangBoolean *showsVerticalScrollIndicator_;
  BOOL showRowDivider_;
  id<FFTViewBehaviorTable_RowProvider> rowProvider_;
  NSString *tableLayoutId_;
  BOOL stickyHeaders_;
  JavaLangDouble *paddingBottom_;
  BOOL scrollToBottomOnLoad_;
}

- (id)initWithFFTKeyValueList:(id<FFTKeyValueList>)properties
withFFTViewBehaviorTable_RowProvider:(id<FFTViewBehaviorTable_RowProvider>)rowProvider;

- (void)setRowProviderWithFFTViewBehaviorTable_RowProvider:(id<FFTViewBehaviorTable_RowProvider>)rowProvider;

- (id)getRowOrSectionAtWithInt:(int)index;

- (long long int)getItemIdWithInt:(int)index;

- (int)getCount;

- (double)getHeightFromObjectWithWithLong:(long long int)id_;

- (NSString *)description;

- (JavaLangDouble *)getRowHeight;

- (JavaLangDouble *)getSectionFooterHeight;

- (JavaLangDouble *)getSectionHeaderHeight;

- (JavaLangDouble *)getHeaderHeight;

- (JavaLangDouble *)getFooterHeight;

- (JavaLangBoolean *)getScrollEnabled;

- (JavaLangBoolean *)getShowsVerticalScrollIndicator;

- (BOOL)isShowRowDivider;

- (id<FFTViewBehaviorTable_RowProvider>)getRowProvider;

- (NSString *)getTableLayoutId;

- (BOOL)isStickyHeaders;

- (JavaLangDouble *)getPaddingBottom;

- (BOOL)isScrollToBottomOnLoad;

- (void)setRowHeightWithJavaLangDouble:(JavaLangDouble *)rowHeight;

- (void)setSectionFooterHeightWithJavaLangDouble:(JavaLangDouble *)sectionFooterHeight;

- (void)setSectionHeaderHeightWithJavaLangDouble:(JavaLangDouble *)sectionHeaderHeight;

- (void)setHeaderHeightWithJavaLangDouble:(JavaLangDouble *)headerHeight;

- (void)setFooterHeightWithJavaLangDouble:(JavaLangDouble *)footerHeight;

- (void)setScrollEnabledWithJavaLangBoolean:(JavaLangBoolean *)scrollEnabled;

- (void)setShowsVerticalScrollIndicatorWithJavaLangBoolean:(JavaLangBoolean *)showsVerticalScrollIndicator;

- (void)setShowRowDividerWithBoolean:(BOOL)showRowDivider;

- (void)setTableLayoutIdWithNSString:(NSString *)tableLayoutId;

- (void)setStickyHeadersWithBoolean:(BOOL)stickyHeaders;

- (void)setPaddingBottomWithJavaLangDouble:(JavaLangDouble *)paddingBottom;

- (void)setScrollToBottomOnLoadWithBoolean:(BOOL)scrollToBottomOnLoad;

- (void)copyAllFieldsTo:(FFTViewBehaviorTable *)other;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorTable_init() {}

J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, rowHeight_, JavaLangDouble *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, sectionFooterHeight_, JavaLangDouble *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, sectionHeaderHeight_, JavaLangDouble *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, headerHeight_, JavaLangDouble *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, footerHeight_, JavaLangDouble *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, scrollEnabled_, JavaLangBoolean *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, showsVerticalScrollIndicator_, JavaLangBoolean *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, rowProvider_, id<FFTViewBehaviorTable_RowProvider>)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, tableLayoutId_, NSString *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorTable, paddingBottom_, JavaLangDouble *)

typedef FFTViewBehaviorTable ComSponbergFluidLayoutViewBehaviorTable;

@protocol FFTViewBehaviorTable_RowProvider < NSObject, JavaObject >

- (NSString *)getRowLayout;

- (id)getRowOrSectionAtWithInt:(int)index;

- (FFTTableRow *)getRowInSectionAtWithInt:(int)sectionIndex
                                  withInt:(int)rowIndex;

- (long long int)getItemIdAtWithInt:(int)index;

- (long long int)getItemIdAtWithInt:(int)sectionIndex
                            withInt:(int)rowIndex;

- (int)getCount;

- (double)getHeightFromObjectWithWithLong:(long long int)id_;

- (FFTTableLayout_TableSection *)getSectionAtWithInt:(int)sectionIndex;

- (int)getNumSections;

- (int)getNumRowsInSectionWithInt:(int)sectionIndex;

- (int)getRowIndexOfObjectWithLong:(long long int)id_;

- (int)getIndexOfRecentlyDeletedObjectWithLong:(long long int)id_;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorTable_RowProvider_init() {}

#endif // _FFTViewBehaviorTable_H_
