//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/ViewBehaviorSearchbar.java
//

#ifndef _FFTViewBehaviorSearchbar_H_
#define _FFTViewBehaviorSearchbar_H_

@class FFTColor;
@protocol FFTKeyValueList;

#import "JreEmulation.h"
#include "com/sponberg/fluid/layout/ViewBehavior.h"

@interface FFTViewBehaviorSearchbar : FFTViewBehavior {
 @public
  NSString *text_;
  FFTColor *textColor_;
  BOOL showCancelButton_;
  NSString *placeholderText_;
  FFTColor *searchBarBackgroundColor_;
}

- (id)initWithFFTKeyValueList:(id<FFTKeyValueList>)properties;

- (NSString *)description;

- (NSString *)getText;

- (FFTColor *)getTextColor;

- (BOOL)isShowCancelButton;

- (NSString *)getPlaceholderText;

- (FFTColor *)getSearchBarBackgroundColor;

- (void)setTextWithNSString:(NSString *)text;

- (void)setTextColorWithFFTColor:(FFTColor *)textColor;

- (void)setShowCancelButtonWithBoolean:(BOOL)showCancelButton;

- (void)setPlaceholderTextWithNSString:(NSString *)placeholderText;

- (void)setSearchBarBackgroundColorWithFFTColor:(FFTColor *)searchBarBackgroundColor;

- (void)copyAllFieldsTo:(FFTViewBehaviorSearchbar *)other;

@end

__attribute__((always_inline)) inline void FFTViewBehaviorSearchbar_init() {}

J2OBJC_FIELD_SETTER(FFTViewBehaviorSearchbar, text_, NSString *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorSearchbar, textColor_, FFTColor *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorSearchbar, placeholderText_, NSString *)
J2OBJC_FIELD_SETTER(FFTViewBehaviorSearchbar, searchBarBackgroundColor_, FFTColor *)

typedef FFTViewBehaviorSearchbar ComSponbergFluidLayoutViewBehaviorSearchbar;

#endif // _FFTViewBehaviorSearchbar_H_
