//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/ViewManager.java
//

#ifndef _FFTViewManager_H_
#define _FFTViewManager_H_

@class FFTColor;
@class FFTFluidApp;
@class FFTLayout;
@class FFTScreen;
@class FFTTab;
@class FFTTableLayout;
@class IOSObjectArray;
@class JavaUtilArrayList;
@class JavaUtilHashMap;
@protocol FFTKeyValueList;

#import "JreEmulation.h"
#include "com/sponberg/fluid/ApplicationInitializer.h"

@interface FFTViewManager : NSObject < FFTApplicationInitializer > {
 @public
  JavaUtilHashMap *screens_;
  JavaUtilHashMap *layouts_;
  JavaUtilHashMap *tableLayouts_;
  id<FFTKeyValueList> colorsByName_;
  id<FFTKeyValueList> sizesByName_;
  id<FFTKeyValueList> fontsByName_;
  id<FFTKeyValueList> fontStyles_;
  JavaUtilArrayList *tabs_;
  double baseUnit_;
  double devicePixelToPixelMultiplier_;
  double devicePixelActualToPixelMultiplier_;
}

- (double)getBaseUnit;

- (void)setBaseUnitWithDouble:(double)baseUnit;

- (void)addScreenWithFFTLayout:(FFTLayout *)layout;

- (void)addLayoutWithFFTLayout:(FFTLayout *)layout;

- (void)addTableLayoutWithFFTTableLayout:(FFTTableLayout *)layout;

- (void)addTabWithFFTTab:(FFTTab *)tab;

- (JavaUtilArrayList *)getTabs;

- (void)initialize__WithFFTFluidApp:(FFTFluidApp *)app OBJC_METHOD_FAMILY_NONE;

- (FFTScreen *)getScreenWithNSString:(NSString *)screenId;

- (FFTLayout *)getLayoutWithNSString:(NSString *)layoutId;

- (FFTTableLayout *)getTableLayoutWithNSString:(NSString *)tableLayoutId;

- (void)setColorsByNameWithFFTKeyValueList:(id<FFTKeyValueList>)colorsByName;

- (void)setSizesByNameWithFFTKeyValueList:(id<FFTKeyValueList>)sizesByName;

- (void)setFontsByNameWithFFTKeyValueList:(id<FFTKeyValueList>)fontsByName;

- (void)setFontStylesWithFFTKeyValueList:(id<FFTKeyValueList>)fontStyles;

- (FFTColor *)getColorWithNSString:(NSString *)name;

- (int)getIntWithNSString:(NSString *)intString;

- (NSString *)getFontFamilyNameWithNSString:(NSString *)refId;

- (NSString *)getFontStyleWithNSString:(NSString *)refId;

- (NSString *)getSpecifiedDefaultFontFamilyName;

- (NSString *)getSpecifiedDefaultFontStyle;

- (NSString *)getSizeWithNSString:(NSString *)name;

- (double)sizeToPixelsWithNSString:(NSString *)size;

- (double)unitsToPixelsWithDouble:(double)units;

- (double)pixelsToPixelsWithDouble:(double)pixels;

- (double)pixelsActualToPixelsWithDouble:(double)pixels;

- (double)pixelsToUnitsWithDouble:(double)pixels;

- (double)fontPointsToPixelsWithDouble:(double)points;

- (double)unitsToFontPointsWithDouble:(double)units;

- (IOSObjectArray *)getSupportedPlatforms;

- (double)getDevicePixelMultiplier;

- (double)getDevicePixelActualMultiplier;

- (void)setDevicePixelMultiplierWithDouble:(double)devicePixelMultiplier;

- (void)setDevicePixelActualMultiplierWithDouble:(double)devicePixelActualMultiplier;

- (id)init;

- (void)copyAllFieldsTo:(FFTViewManager *)other;

@end

__attribute__((always_inline)) inline void FFTViewManager_init() {}

J2OBJC_FIELD_SETTER(FFTViewManager, screens_, JavaUtilHashMap *)
J2OBJC_FIELD_SETTER(FFTViewManager, layouts_, JavaUtilHashMap *)
J2OBJC_FIELD_SETTER(FFTViewManager, tableLayouts_, JavaUtilHashMap *)
J2OBJC_FIELD_SETTER(FFTViewManager, colorsByName_, id<FFTKeyValueList>)
J2OBJC_FIELD_SETTER(FFTViewManager, sizesByName_, id<FFTKeyValueList>)
J2OBJC_FIELD_SETTER(FFTViewManager, fontsByName_, id<FFTKeyValueList>)
J2OBJC_FIELD_SETTER(FFTViewManager, fontStyles_, id<FFTKeyValueList>)
J2OBJC_FIELD_SETTER(FFTViewManager, tabs_, JavaUtilArrayList *)

typedef FFTViewManager ComSponbergFluidLayoutViewManager;

#endif // _FFTViewManager_H_
