//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src-delomboked/com/sponberg/fluid/layout/WebviewActionListener.java
//

#include "com/sponberg/fluid/layout/WebviewActionListener.h"

@interface FFTWebviewActionListener : NSObject
@end

@implementation FFTWebviewActionListener

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "actionPerformedWithNSString:", "actionPerformed", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _FFTWebviewActionListener = { "WebviewActionListener", "com.sponberg.fluid.layout", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_FFTWebviewActionListener;
}

@end
